### ISSUE TITLE
[Bug] Failed to find log texture for bark betternether:nether_reed

### ISSUE THREAD

**Issue by TobiPeterG** [quiqueck/BetterNether#103]
### What happened?

Hey there,
when starting Minecraft, I get the following error in the logs:
[Render thread/ERROR]: Failed to find log texture for bark betternether:nether_reed
java.io.IOException: java.util.NoSuchElementException: No value present
	at net.mehvahdjukaar.moonlight.api.resources.textures.SpriteUtils.readImage(SpriteUtils.java:28) ~[moonlight-1.19.2-2.1.27-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.textures.TextureImage.open(TextureImage.java:149) ~[moonlight-1.19.2-2.1.27-fabric.jar:?]
	at com.ordana.immersive_weathering.dynamicpack.ClientDynamicResourcesHandler.lambda$regenerateDynamicAssets$9(ClientDynamicResourcesHandler.java:264) ~[immersive_weathering-1.19.2-1.2.5-fabric.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at com.ordana.immersive_weathering.dynamicpack.ClientDynamicResourcesHandler.regenerateDynamicAssets(ClientDynamicResourcesHandler.java:256) ~[immersive_weathering-1.19.2-1.2.5-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceProvider.reloadResources(DynResourceProvider.java:111) ~[moonlight-1.19.2-2.1.27-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceProvider.onEarlyReload(DynResourceProvider.java:81) ~[moonlight-1.19.2-2.1.27-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.lambda$postEvent$1(MoonlightEventsHelperImpl.java:23) ~[moonlight-1.19.2-2.1.27-fabric.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.postEvent(MoonlightEventsHelperImpl.java:23) ~[moonlight-1.19.2-2.1.27-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.events.MoonlightEventsHelper.postEvent(MoonlightEventsHelper.java) ~[moonlight-1.19.2-2.1.27-fabric.jar:?]
	at net.minecraft.class_6861.handler$dbf000$dynamicPackEarlyReload(class_6861.java:1534) ~[client-intermediary.jar:?]
	at net.minecraft.class_6861.<init>(class_6861.java:60) ~[client-intermediary.jar:?]
	at org.quiltmc.qsl.resource.loader.impl.ResourcePackRegistrationContextImpl.<init>(ResourcePackRegistrationContextImpl.java:43) ~[resource_loader-3.0.0-beta.25+1.19.2.jar-d623264a-db32-4366-a92a-caf8d5d6764d-nested.jar:?]
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.buildMinecraftResourcePack(ResourceLoaderImpl.java:397) ~[resource_loader-3.0.0-beta.25+1.19.2.jar-d623264a-db32-4366-a92a-caf8d5d6764d-nested.jar:?]
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.buildMinecraftResourcePack(ResourceLoaderImpl.java:408) ~[resource_loader-3.0.0-beta.25+1.19.2.jar-d623264a-db32-4366-a92a-caf8d5d6764d-nested.jar:?]
	at net.minecraft.class_1066.handler$fnc001$onPackGet(class_1066.java:555) ~[client-intermediary.jar:?]
	at net.minecraft.class_1066.method_4635(class_1066.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_3288.method_14458(class_3288.java:85) ~[client-intermediary.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) [?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) [?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) [?:?]
	at net.minecraft.class_3283.method_29211(class_3283.java:95) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:646) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:205) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.17.8.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.17.8.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.8.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:143) ~[?:?]
	at net.mehvahdjukaar.moonlight.api.resources.textures.SpriteUtils.readImage(SpriteUtils.java:25) ~[moonlight-1.19.2-2.1.27-fabric.jar:?]
	... 39 more

### BetterNether

7.1.2

### BCLib

2.1.5

### Fabric API

Quilt with FAPI 0.72

### Fabric Loader

Quilt loader 0.17.8

### Minecraft

1.19.2

```shell
Mods:
  [✔] 3dskinlayers-fabric-1.5.2-mc1.19.1
  [✔] AdditionalStructures-1.19.x-(v.4.1.1)
  [✔] Adorn-3.8.1+1.19.2-fabric
  [✔] advancementinfo-1.19.1-fabric0.58.5-1.3.1
  [✔] AdvancementPlaques-1.19.2-fabric-1.4.6
  [✔] advancements-enlarger-0.3.0-1.19.2
  [✔] advancementscreenshot-1.19.2-4.0
  [✔] AmbientEnvironment-fabric-1.19.2-8.0+3
  [✔] AmbientSounds_FABRIC_v5.2.13_mc1.19.2
  [✔] Amplified_Nether_v1.2
  [✔] animatica-0.5+1.19
  [✘] antiqueatlas-7.0.3-fabric-mc1.18.2.jar (disabled)
  [✔] appleskin-fabric-mc1.19-2.4.1
  [✔] appliedenergistics2-fabric-12.9.2
  [✔] architectury-6.4.62-fabric
  [✔] ArmorSoundTweak-6.0.0-fabric
  [✔] auditory-0.0.4-1.19.x
  [✔] auto_third_person-fabric-1.19.2-1.2.1
  [✘] autohud-2.5+1.19.1.jar (disabled)
  [✔] auudio_fabric_1.0.3_MC_1.19
  [✔] awesomedungeon-fabric-1.19.2-3.0.0
  [✔] awesomedungeonend-fabric-1.19.2-3.0.0
  [✔] awesomedungeonnether-fabric-1.19.2-3.0.0
  [✔] awesomedungeonocean-fabric-1.19.2-3.0.1
  [✔] balm-fabric-4.5.2+0
  [✔] bclib-2.1.5
  [✔] beautifiedchatserver-1.19.2-2.0
  [✔] better-end-2.1.2
  [✔] better-nether-7.1.2
  [✔] BetterAdvancements-Fabric-1.19.2-0.3.0.148
  [✔] betteranimalmodels-1.19-5.6.0-fabric
  [✔] betterbiomeblend-1.19.0-1.3.6-fabric
  [✔] bettercombat-fabric-1.5.4+1.19
  [✔] bettermounthud-1.2.0
  [✔] bettertaskbar-fabric-mc1.18.2-mc1.19.2-1.5.1
  [✔] BetterThirdPerson-Fabric-1.19-1.9.0
  [✔] bettervillage-fabric-1.19.2-2.0.0
  [✔] blur-2.6.0
  [✔] BOMD-1.4.6-1.19.2
  [✔] Bookshelf-Fabric-1.19.2-16.2.16
  [✔] Botania-1.19.2-436-FABRIC
  [✔] CameraOverhaul-1.4.0-fabric-universal
  [✔] cardinal-components-api-5.0.2
  [✔] cave-enhancements-1.19.2-2.1.7-fabric
  [✔] celib-1.1.0+1.19
  [✘] cem-0.7.1.jar (disabled)
  [✘] charm_fixer-1.0.0.jar (disabled)
  [✔] charm-fabric-1.19.2-4.4.4
  [✔] charmofundying-fabric-6.0.0+1.19.2
  [✔] charmonium-fabric-1.19.2-4.2.1
  [✘] chime-1.4.0.jar (disabled)
  [✘] chipped-2.0.0-fabric.jar (disabled)
  [✔] chisel-1.4.7+1.19.2
  [✔] CITResewn-1.1.2+1.19.2
  [✔] cleancut-1.19.2-5.1-fabric
  [✔] clear-skies-fabric-mc119-2.0.95
  [✔] cloth-config-8.2.88-fabric
  [✔] collective-1.19.2-6.26
  [✔] colormatic-3.1.2+mc.1.19
  [✔] consistency_plus-fabric-0.5.1+1.19.2
  [✔] continuity-2.0.1+1.19
  [✘] coralreef-fabric-1.18.2-1.0.2.jar (disabled)
  [✔] CraftPresence-2.0.0-alpha.3+1.19.2
  [✔] create-fabric-0.5.0g-796+1.19.2
  [✔] createaddition+1.19.2-1.19.2-20221218a
  [✔] createdeco-1.2.12-1.19.2
  [✔] CreativeCore_FABRIC_v2.9.3_mc1.19.2
  [✔] creeperoverhaul-2.0.5-fabric
  [✔] Croptopia-1.19.2-FABRIC-2.2.1
  [✔] croptopia-chocolaterie-1.2-1.19
  [✔] cullleaves-fabric-3.0.1
  [✔] dark-enchanting-1.0.0+1.19.1
  [✔] darkness-fabric-mc119-2.0.101
  [✔] DarkPaintings-Fabric-1.19.2-13.1.4
  [✔] dashloader-4.1.3+1.19
  [✘] dashloader-5.0.0-alpha.6+1.19.2.jar (disabled)
  [✔] dawn-3.5.0
  [✔] dehydration-1.3.3
  [✔] DiagonalFences-v4.2.3-1.19.2-Fabric
  [✔] doubledoors-1.19.2-4.0
  [✔] DripSounds-1.19-0.3.0
  [✔] dynamic-fps-2.2.0
  [✔] dynamiccrosshair-5.0+1.19.2-fabric
  [✔] dynamiccrosshair-compat-3.0+1.19.2
  [✔] DynamicSoundFilters-1.3.0+1.19
  [✔] DynamicSurroundings-RemasteredFabric-1.19-0.1.1
  [✔] ecologics-fabric-1.19.2-2.1.11
  [✔] eden-ring-0.6.4
  [✔] effective-1.6+1.19.2
  [✔] elytraslot-fabric-6.0.0+1.19.2
  [✔] enchanted-vertical-slabs-1.6
  [✔] EnchantmentDescriptions-Fabric-1.19.2-13.0.14
  [✔] enhancedblockentities-0.7.2+1.19.2
  [✔] entityculling-fabric-1.5.2-mc1.19
  [✔] environmentz-1.3.5
  [✔] evs-betterend-1.1.0
  [✔] exlinecopperequipment-fabric-1.19.2-v2.1.2
  [✔] extraalchemy-fabric-1.19.2-1.9.0
  [✔] extraorigins-1.19-2
  [✔] extrasounds-2.3.1+1.19.2-1.19.1
  [✔] fabric-diagonal-panes-0.6.4
  [✔] fabric-enchantments-0.9.0
  [✔] fabric-language-kotlin-1.9.0+kotlin.1.8.0
  [✔] fabric-seasons-1.4-BETA+1.19
  [✔] fallingleaves-1.13.0+1.19.2
  [✔] FallingTree-1.19.2-3.10.0
  [✔] fancymenu_fabric_2.13.2_MC_1.19-1.19.2
  [✔] ferritecore-5.0.3-fabric
  [✔] fm_audio_extension_fabric_1.1.1_MC_1.19
  [✔] ForgeConfigAPIPort-v4.2.10-1.19.2-Fabric
  [✔] friendsandfoes-flowerymooblooms-quilt-mc1.19.2-1.0.0
  [✔] friendsandfoes-quilt-mc1.19.2-1.6.7
  [✔] geckolib-quilt-1.19-3.1.40
  [✔] genesis-1.19-1.0.2
  [✔] grind-enchantments-2.0.0+1.19.2
  [✔] handoveryouritems-1.19.2-3.0
  [✔] hardcorerevival-fabric-1.19.2-9.0.1
  [✔] health-levels-1.0.3
  [✔] HealthOverlay-1.19.2-7.2.3
  [✔] Iceberg-1.19.1-fabric-1.0.46
  [✔] IKnowWhatImDoing-4.1.0-fabric
  [✔] illuminations-1.10.11
  [✔] immersive_weathering-1.19.2-1.2.5-fabric
  [✔] immersive-portals-2.3.1-mc1.19.2-fabric
  [✔] improvedmobs-1.19-1.11.0-fabric
  [✔] indium-1.0.9+mc1.19.2
  [✘] inmis-2.7.1-1.19.jar (disabled)
  [✘] InventorySorter-1.8.10-1.19.jar (disabled)
  [✔] iris-mc1.19.2-1.4.5
  [✔] Jade-1.19.1-fabric-8.7.3
  [✔] jobsaddon-1.0.8
  [✔] konkrete_fabric_1.6.0_MC_1.19.1-1.19.2
  [✔] krypton-0.2.1
  [✔] lambdabettergrass-1.3.0+1.19
  [✔] lambdynamiclights-2.2.0+1.19.2
  [✔] lazydfu-0.1.3
  [✔] levelz-1.4.4
  [✔] libraryferret-fabric-1.19.2-3.0.0
  [✔] lithium-fabric-mc1.19.2-0.10.4
  [✔] Llamarama-1.8.4
  [✔] map-atlases-2.3.1+1.19
  [✔] MaxHealthFix-Fabric-1.19.2-8.0.1
  [✔] mcw-bridges-2.0.6-mc1.19.2fabric
  [✔] mcw-paintings-1.0.4fabric-mc1.19.2
  [✔] medieval-origins-1.19.x-4.1.3
  [✔] midnightcontrols-1.7.4+1.19
  [✔] MinecraftCapes Fabric 1.19.2-12.2.2
  [✘] minegate-moreblocks-1.2.5.jar (disabled)
  [✔] moderate-loading-screen-1.1.3+1.19
  [✔] modmenu-4.1.2
  [✔] moonlight-1.19.2-2.1.27-fabric
  [✔] morevillagers-fabric-1.19-4.0.2
  [✔] MouseTweaks-fabric-mc1.19-2.22
  [✔] mousewheelie-1.10.7+mc1.19.2
  [✔] namepain-1.4.0 fabric-1.19.x
  [✔] nametagtweaks-1.19.2-3.0
  [✔] naturalist-fabric-2.1.1-1.19.2
  [✔] NaturesCompass-1.19.2-2.1.0-fabric
  [✔] netherportalspread-1.19.2-7.1
  [✔] NorthernCompass-Fabric-1.19.3-1.0.14
  [✔] numismatic-overhaul-0.2.8+1.19
  [✔] Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.13
  [✔] Origins-1.19.2-1.7.1
  [✔] ostOverhaul-0.2.6-1.19.1
  [✔] owo-lib-0.9.3+1.19
  [✔] oxidized-1.7.2
  [✔] paradise-lost-2.0.2-beta+1.19.2
  [✔] Patchouli-1.19.2-77-FABRIC
  [✔] Pehkui-3.6.3+1.14.4-1.19.3
  [✔] player-animation-lib-fabric-0.4.0
  [✔] polymorph-fabric-0.46.1+1.19.2
  [✔] PresenceFootsteps-1.6.4
  [✔] promenade-2.7.1
  [✔] PuzzlesLib-v4.3.12-1.19.2-Fabric
  [✔] qfapi-4.0.0-beta.26_qsl-3.0.0-beta.25_fapi-0.72.0_mc-1.19.2
  [✔] realisticsleep-1.6.0
  [✔] reeses_sodium_options-1.4.9+mc1.19.2-build.67
  [✔] refabslab-0.7.4+1.19
  [✔] repurposed_structures_fabric-6.1.3+1.19.2
  [✔] respro-0.2.2+1.19
  [✔] revelationary-1.1.0
  [✔] scout-1.19.2-1.1.2
  [✔] simplyswords-fabric-1.37-1.19.2
  [✔] sodium-extra-0.4.16+mc1.19.2-build.90
  [✔] sodium-fabric-mc1.19.2-0.4.4+build.18
  [✔] soundphysics-fabric-1.19.2-1.0.18
  [✘] soundphysics-fabric-1.19.2-1.0.18.jar (disabled)
  [✔] spiceoffabric-1.6.0-beta.2+1.19.2
  [✔] spiderstpo-fabric-1.19.2-2.0.3
  [✔] spyglass-improvements-1.4+mc1.19+fabric
  [✔] stackrefill-1.19.2-4.0
  [✔] starlight-1.1.1+fabric.ae22326
  [✔] stonecutter_recipe_tags-4.2.1+1.19.5861878.fabric
  [✔] supplementaries-1.19.2-2.2.35-fabric
  [✔] tbls-0.0.1_1.19.2
  [✔] tenshilib-1.19-1.6.14-fabric
  [✔] TerraBlender-fabric-1.19.2-2.0.1.136
  [✔] Terralith_v2.3.6
  [✔] Tips-Fabric-1.19.2-8.0.27
  [✔] TravelersTitles-1.19.2-Fabric-3.1.0
  [✔] traverse-6.0.6
  [✔] trinkets-3.4.1
  [✔] twilightforest-1.19.2-4.2.1493-universal
  [✔] voicechat-fabric-1.19.2-2.3.27
  [✔] weaponmaster-multi-fabric-1.19-3.0.2
  [✔] wildlife-1.19.2-2.2
  [✔] wraith-waystones-3.0.5+mc1.19.2
  [✘] WWOO-FABRIC-3.1.11.jar (disabled)
  [✔] xlpackets-1.19.2-4
  [✔] youritemsaresafe-1.19.2-3.0
  [✔] YungsApi-1.19.2-Fabric-3.8.2
  [✔] YungsBetterDesertTemples-1.19.2-Fabric-2.2.1
  [✔] YungsBetterDungeons-1.19.2-Fabric-3.2.1
  [✔] YungsBetterMineshafts-1.19.2-Fabric-3.2.0
  [✔] YungsBetterStrongholds-1.19.2-Fabric-3.2.0
  [✔] YungsBetterWitchHuts-1.19.2-Fabric-2.1.0
  [✔] YungsBridges-1.19.2-Fabric-3.1.0
  [✔] YungsExtras-1.19.2-Fabric-3.1.0
```

**Comment by quiqueck** [comment]
Thanks for reporting. From the message, this appears to be an issue with moonlight-lib? Did you contact the devs over there already? Is not, would you please mention this issue on their tracker as well, so I can keep track?
