### ISSUE TITLE
[Bug] Server crashes after deactivating items trough config.

### ISSUE THREAD

**Issue by nytethc** [quiqueck/BetterNether#104]
### What happened?

When setting items like Tools, e.g. Nether Ruby Pickaxe to false trough the Config, the server crahes with following output:

### BetterNether

7.1.2

### BCLib

2.1.5

### Fabric API

0.7.2.0

### Fabric Loader

0.14.12

### Minecraft

1.19.2

### Relevant log output

```shell
java.lang.IllegalStateException: Some intrusive holders were not added to registry: [Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}]
	at net.minecraft.class_2370.method_40276(class_2370.java:352)
	at net.minecraft.class_2378.method_40292(class_2378.java:404)
	at net.minecraft.server.MinecraftServer.handler$bln001$beforeSetupServer(MinecraftServer.java:6792)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Other Mods

```shell
Connectivity[Forge/Fabric] (by someaddon)
    Reese's Sodium Options (by FlashyReese)
    DragonLoot (by pois1xlive)
    Equipment Compare [Fabric] (by Grend_G)
    Zoomify (by XanderIsDev)
    FTB Chunks (Fabric) (by FTB)
    Reacharound (by spAnser)
    Better Animations Collection (by Fuzs_)
    Better Beacon Placement (by Serilum)
    Spryzeen's Scarlet glint (by Spryzeen__)
    MidnightLib (by TeamMidnightDust)
    Iceberg [Fabric] (by Grend_G)
    Repurposed Structures (Quilt/Fabric) (by telepathicgrunt)
    LambdaBetterGrass (by LambdAurora)
    Iris Shaders (by coderbot)
    Climb Ladders Fast [Fabric/Forge] (by spoorn)
    Mod Menu (by ProspectorDev)
    Another Furniture (by Starfish_Studios)
    Jade Addons (Fabric) (by Snownee_)
    YUNG's Better Ocean Monuments (Fabric) (by YUNGNICKYOUNG)
    YUNG's Better Strongholds (Fabric) (by YUNGNICKYOUNG)
    Trinkets (Fabric) (by EmilyPloszaj)
    ShulkerBoxTooltip [Fabric/Forge] (by MisterPeModder)
    YUNG's Better Desert Temples (Fabric) (by YUNGNICKYOUNG)
    YUNG's Bridges (Fabric) (by YUNGNICKYOUNG)
    Rotten Leather(Fabric) (by FirelightDev)
    Bartering Station (by Fuzs_)
    ItemPhysic Full (by CreativeMD)
    LambDynamicLights (by LambdAurora)
    Water Improved (by HotTubBug)
    Double Doors (by Serilum)
    Make Bubbles Pop [Fabric] (by Tschipcraft)
    Nyf's Spiders (by theNyfaria)
    Inventory HUD+ (by dmitrylovin)
    Roughly Enough Loot Tables (by GrigLog)
    TooltipRareness (by Globox_Z)
    Simple Grass Flowers (by JamieProbably)
    Slightly Improved Font (32x) (by LatvianModder)
    Dramatic Skys (by thebaum64)
    BetterEnd (by Quiqueck)
    Default Options (Fabric Edition) (by BlayTheNinth)
    Illuminations 🔥 (by doctor4t)
    YDM's Weapon Master (by YourDailyModderx)
    Chat Heads (by dzwdz)
    Sodium Extra (by FlashyReese)
    Diamond Nuggets (by SamDev7)
    Naturalist (by Starfish_Studios)
    Fabric API (by modmuss50)
    Puzzles Lib (by Fuzs_)
    Forge Config API Port (by Fuzs_)
    Linear XP (by colderlavalamp)
    Custom Entity Models (CEM) (by dorianpb)
    Moonlight Lib (by MehVahdJukaar)
    Infinite Trading (by Serilum)
    YUNG's Better Dungeons (Fabric) (by YUNGNICKYOUNG)
    Deeper and Darker (by KyaniteMods)
    Cardinal Components (by UpcraftLP)
    Tool Stats (by DarkhaxDev)
    CoralReef (by primetoxinz)
    Indium (by comp500)
    SlimyFloor (by Pouille)
    Fresh Animations (by Fresh__LX)
    AmbientSounds 5 (by CreativeMD)
    Stefan's armors 'N' items (by stefanj2_)
    FTB Teams (Fabric) (by FTB)
    Keyboard Wizard (by mrnerdy42)
    Roughly Enough Professions (REP) (by Mrbysco)
    Trash Can (Fabric) (by farruchoo)
    Tumbleweed (by bconv)
    Sound Physics Remastered (by henkelmax)
    Bottle Your Xp (by Serilum)
    YUNG's API (Fabric) (by YUNGNICKYOUNG)
    YUNG's Extras (Fabric) (by YUNGNICKYOUNG)
    FabricSkyboxes (by AMereBagatelle)
    Time To Live (by Schauweg)
    AppleSkin (by squeek502)
    Show Me What You Got (by Apace100)
    Roughly Enough Items Fabric/Forge (REI) (by shedaniel)
    Continuity (by Pepper_Bell)
    Don't Clear Chat History (by anar4732)
    Trading Post (by Fuzs_)
    Inventory Profiles Next (by mirinimi)
    WorldEdit (by sk89q)
    JourneyMap (by techbrew)
    Charm (by svenhjol)
    BCLib (by Quiqueck)
    Visual Workbench (by Fuzs_)
    FTB Library (Fabric) (by FTB)
    Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)
    Sit (Fabric) (by bl4ckscor3)
    Not Enough Animations (by tr9zw)
    Collective (by Serilum)
    Crafting Tweaks (Fabric Edition) (by BlayTheNinth)
    Inventorio (Fabric) (by Lizard_OfOz)
    Tissou's Zombie Pack (by Tissou)
    Carry On (by Tschipp)
    Classic Faithful 64x (by Faithful_Resource_Pack)
    Quick Shulker (by Kyrptonaught)
    Blinking Ender Eyes (by Futureazoo)
    YUNG's Better Witch Huts (Fabric) (by YUNGNICKYOUNG)
    Balm (Fabric Edition) (by BlayTheNinth)
    Transparent (by Trikzon)
    MCPitanLibarch (Fabric/Forge) (by pitan76)
    KleeSlabs (Fabric Edition) (by BlayTheNinth)
    Falling Leaves (Fabric) (by RandomMcSomethin)
    ESSENTIAL Mod (by SparkUniverse_)
    YUNG's Better Mineshafts (Fabric) (by YUNGNICKYOUNG)
    Clumps (by Jaredlll08)
    CIT Resewn (by SHsuperCM)
    Effective 💦 (by doctor4t)
    Furnace Recycle (by Serilum)
    Eating Animation [Fabric] (by theone_ss)
    Supplementaries (by MehVahdJukaar)
    Controlling (by Jaredlll08)
    Diagonal Fences (by Fuzs_)
    Fantasy 3D Weapons CIT (by nongko18)
    River Redux (by SuperCoder79)
    Starlight (Fabric) (by Spottedstar)
    Leaves Be Gone (by Fuzs_)
    Jade 🔍 (by Snownee_)
    Smaller Nether Portals (by Serilum)
    GeckoLib (by ThanosGecko)
    Obsidian Ender Chest (by TinyDaggsy)
    Traveler's Backpack [Fabric] (by Tiviacz1337)
    Configured (Fabric) (by MrCrayfish)
    CreativeCore (by CreativeMD)
    Dark Mode Everywhere - Fabric (by HeyAmAK9)
    Lootr (Fabric) (by Noobanidus)
    Easy Anvils (by Fuzs_)
    Icarus (by Camellias_)
    [Fabric] Progressive Bosses (by anar4732)
    BetterNether (by Quiqueck)
    JourneyMap Integration (by frankv_)
    Lithium (Fabric) (by jellysquid3_)
    Better Block Sounds (by OrdanaryMods)
    Cloth Config API (Fabric/Forge) (by shedaniel)
    YetAnotherConfigLib (by XanderIsDev)
    EmeraldExtended Forge and Fabric (Emerald Mod) (by drdefenestration)
    Skin Layers 3D (Fabric/Forge) (by tr9zw)
    More Geodes (by TheDeathlyCow)
    FTB Ranks (Fabric) (by FTB)
    Crawl (Fabric) (by fewizz_)
    Emerald Apple (by zeton54)
    Fabric Seasons (by D4rkness_King)
    Tips (by DarkhaxDev)
    Better Third Person (by Socolio)
    Easy Magic (by Fuzs_)
    TreeAxe [FABRIC] (by kwpugh)
    AttributeFix (by DarkhaxDev)
    Fancy Beds (by Agente_511)
    Visuality (by PinkGoosik)
    Satin API (by PyrofabTheModsmith)
    Roughly Enough Resources (by theorbagain)
    Icons (by mr_ch0c0late1)
    TerraBlender (Fabric) (by TheAdubbz)
    You're in Grave Danger (by b1n_ry)
    DashLoader (by notequalalpha)
    Entity Texture Features - [Fabric & Forge] (by traben_0)
    Bookshelf (by DarkhaxDev)
    Pick Up Notifier (by Fuzs_)
    Paintings ++ (by AbsolemJackdaw)
    Duckling (by Frogipher)
    Architectury API (Fabric/Forge) (by shedaniel)
    Easy Elytra Takeoff (by Serilum)
    Go Fish (by Draylar1)
    Max Enchant X (by the_zyga)
    libIPN (by mirinimi)
    No Recipe Book (Fabric) (by Grayray_75)
    Polymorph (Fabric) (by TheIllusiveC4)
    Simple Uncrafting Table (Fabric/Forge) (by pitan76)
    Enchantment Descriptions (by DarkhaxDev)
    Quartz Elevator (by atonkish)
    Fabric Language Kotlin (by modmuss50)
    Enhanced Boss Bars (by nakuuuh)
    Dragonyte's UI (by nyteTHC)
    Sodium (by jellysquid3_)
    Villagers Drop Emeralds on Death (by exlinegames)
    Roughly Enough Trades (by GrigLog)
    Mouse Tweaks (by YaLTeR)
```

**Comment by PlazmaKG** [comment]
This happens for me too. I want to disable Ruby & Diamond Cincinnasite Tools because they're overpowered. However, whenever I change them to false in the config, the game just crashes.

**Comment by nytethc** [comment]
> 

i feel you, tbh i just dont want any tools & weapons besides the vanilla ones, but i wanna keep the cool additions from the mod itself! i hope it gets fixed soon.

**Comment by nytethc** [comment]
> This happens for me too. I want to disable Ruby & Diamond Cincinnasite Tools because they're overpowered. However, whenever I change them to false in the config, the game just crashes.

i feel you, tbh i just dont want any tools & weapons besides the vanilla ones, but i wanna keep the cool additions from the mod itself! i hope it gets fixed soon.

**Comment by CryingEnder** [comment]
Same issue here. I hope this gets a fix.
