### ISSUE TITLE
[Bug] Server crashes rendering blocks in Nether

### ISSUE THREAD

**Issue by micahflack** [quiqueck/BetterNether#106]
### What happened?

When entering the Nether, if the player renders the Barrel Cactus or Agave blocks the server crashes. These are the only ones we have noticed so far.

### BetterNether

7.1.1 and 7.1.2

### BCLib

2.1.5

### Fabric API

0.71.0+1.19.2

### Fabric Loader

0.14.12

### Minecraft

1.19.2

### Relevant log output

```shell
Description: Colliding entity with block
 
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.lang.ThreadLocal.get()" is null
	at net.minecraft.class_1309.handler$zcg000$port_lib$spawnDropsTAIL(class_1309.java:5701)
	at net.minecraft.class_1309.method_16080(class_1309.java:1397)
	at net.minecraft.class_1309.method_6078(class_1309.java:1348)
	at net.minecraft.class_1309.method_5643(class_1309.java:1204)
	at net.minecraft.class_1429.method_5643(class_1429.java:80)
	at org.betterx.betternether.blocks.BlockBarrelCactus.method_9548(BlockBarrelCactus.java:78)
	at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:952)
	at net.minecraft.class_1297.method_5852(class_1297.java:1059)
	at net.minecraft.class_1297.method_36974(class_1297.java:783)
	at net.minecraft.class_1297.method_5784(class_1297.java:752)
	at net.minecraft.class_1309.method_26318(class_1309.java:2282)
	at net.minecraft.class_1309.method_6091(class_1309.java:2227)
	at net.minecraft.class_1309.method_6007(class_1309.java:2680)
	at net.minecraft.class_1308.method_6007(class_1308.java:553)
	at net.minecraft.class_1296.method_6007(class_1296.java:127)
	at net.minecraft.class_1429.method_6007(class_1429.java:57)
	at net.minecraft.class_1309.method_5773(class_1309.java:2385)
	at net.minecraft.class_1308.method_5773(class_1308.java:353)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.handler$cjd000$modifiedRunLoop(MinecraftServer.java:7885)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Other Mods

```shell
Fabric Mods: 
		ad_astra: Ad Astra! 1.12.2
		additionaladditions: Additional Additions 5.1.0
		additionalbars: Additional Bars 3.3.1+1.19
		adorn: Adorn 3.8.1+1.19.2
		advanced_reborn: Advanced Reborn 1.1.3
		advdebug: Advancements Debug 2.3.0
		adventurez: AdventureZ 1.4.17
		ae2: Applied Energistics 2 12.9.2
		ae2wtlib: AE2WTLib 12.8.5
		allay: YDM's Allay Mod 4.1.0
		alloy_forgery: Alloy Forgery 2.0.17+1.19
		almostunified: AlmostUnified 1.19.2-0.3.3
		amecs: Amecs 1.3.8+mc.1.19-rc2
		animal_origins_18: Animal Origins 1.0.0
		appbot: Applied Botanics 1.4.1
		appleskin: AppleSkin 2.4.1+mc1.19
		arcanus: Arcanus 1.30
		architects_palette: Architect's Palette Fabric 2.1.1
		architectury: Architectury 6.4.62
		archon: Archon 0.4.1
		armorstatues: Armor Statues 4.0.3
		artifacts: Artifacts 7.1.1+fabric
			expandability: ExpandAbility 6.0.0
		artis: Artis-Recrafted 2.5.0+1.19
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
		attributefix: AttributeFix 17.1.3
		auto-workstations: Auto Workstations v1.0-SNAPSHOT-19
		autoconfig1u: Auto Config v1 Updated 3.4.0
		automobility: Automobility 0.4.1+1.19.2-fabric
			jsonem: JsonEM 0.1.2+1.19
		autotag-convention: AutoTag Convention 2.0.0+1.19
			autotag: AutoTag 2.0.0+1.19
		badpackets: Bad Packets 0.2.1
		balm-fabric: Balm 4.5.2+0
		bcc: BetterCompatibilityChecker 2.0.2-build.16+mc1.19.1
		bclib: BCLib 2.1.5
		bedbenefits: BedBenefits 9.1.2
		beenfo: Beenfo 1.19.1-fabric0.58.5-1.3.3
			crowdin-translate: CrowdinTranslate 1.4+1.19
		besmirchment: Besmirchment 1.19-7
		bettercombat: Better Combat 1.5.4+1.19
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.1
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterend: Better End 2.1.2
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		betternether: Better Nether 7.1.1
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		bewitchment: Bewitchment 1.19-6
		bhmenu: BHMenu-Fabric 1.19-1.3
		bitsandchisels: BitsAndChisels 2.7.0
			stacc: Stacc 1.3.4
		blockus: Blockus 2.5.6+1.19.2
		boatcontainer: BoatContainer 1.2.4
		bookshelf: Bookshelf 16.2.16
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.6-1.19.2
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		botania: Botania 1.19.2-436-FABRIC
		botarium: Botarium 1.8.2
		brewinandchewin: Brewin And Chewin fabric-1.0.5+1.19.2
		buildinggadgets: st'ructure tools 1.0.30
			mm: Manningham Mills 2.3
		byg: Oh The Biomes You'll Go 2.0.0.13
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		cacao: Croptopia's Chocolaterie 1.2
		capybara: Capybara 2.0.1
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
		carpet: Carpet Mod 1.4.84
		carpet-extra: Carpet Extra 1.4.84
		carryon: Carry On 2.0.2.3
		catwalksinc: Catwalks Inc. 1.3.1
		chalk: Chalk 2.1.0+1.19
		chisel: Chisel Refabricated 1.4.5
		chococraft: Chococraft 4 0.6.4
		chubbystuff: Chubby Stuff 2.0.1-fabric
		climbladdersfast: ClimbLaddersFast 3.0.5-1.19
		cloth-api: Cloth API 4.0.65
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+14
		compactmachines: Compact Machines 5 5.1.0-fabric
		computercraft: CC: Restitched 1.101.2
			io_netty_netty-codec-http: netty-codec-http 4.1.77.Final
			org_squiddev_cobalt: Cobalt 0.5.5
		conjuring: Conjuring 1.0.26+1.19
		connectivity: Connectivity Mod 1.19.2-3.7
		consistency_plus: Consistency Plus 0.5.1+1.19.2
			stonecutter_recipe_tags: Stonecutter Recipe Tags 4.0.0+1.19.9b8d04c.fabric
		cookingforblockheads: Cooking for Blockheads 13.3.0
		coxinhautilities: Coxinha Utilities 1.4.5+1.19
		craftingtweaks: Crafting Tweaks 15.1.0
		crawl: Crawl 0.11.1
		create: Create 0.5.0g-796+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.5.0
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			registrate-fabric: Registrate for Fabric 1.1.44-MC1.19.2
		createaddition: Create Crafts & Additions ${version}
		creativecore: CreativeCore (Fabric) 2.9.3
		creaturesfromthesnow: Creatures from The Snow 4.0.1+1.19.2
		creeperoverhaul: Creeper Overhaul 2.0.5
		crittersandcompanions: Critters and Companions 1.19.2-1.0.3
		croparia: Croparia 4.0.0
		croptopia: Croptopia 2.2.1
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		croptosis: Croptosis 1.5.1
		culturaldelights: Cultural Delights Fabric 0.14.9+1.19.2
			terraform-wood-api-v1: Terraform Wood API (v1) 4.2.0
		damagetilt: Damage Tilt 1.19-fabric-0.1.2
		dankstorage: Dank Storage 1.19.2-4.3
		dark-enchanting: Dark Enchanting 1.0.0+1.19.1
		dataattributes: Data Attributes 1.4.0
		deathlog: DeathLog 0.2.11+1.19
		decorative_blocks: Decorative Blocks 3.0.0
		deeperdarker: Deeper and Darker 1.1.6
			customportalapi: Custom Portal Api 0.0.1-beta54-1.19
			paragon: Paragon 3.0.2
				com_moandjiezana_toml_toml4j: toml4j 0.7.2
				org_yaml_snakeyaml: snakeyaml 1.27
		dimdoors: DimensionalDoors 5.0.2
			com_flowpowered_flow-math: flow-math 1.0.3
			com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
			matrix: Matrix 1.0.0
			org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
		disenchanter: Disenchanter 0.1.7+1.19
		dml-refabricated: Deep Mob Learning: Refabricated 0.5.7-BETA-build1
			dml-refabricated-base: DML: Refabricated - Base 0.5.7-BETA-build1
			dml-refabricated-events: DML: Refabricated - Vanilla Events 0.5.7-BETA-build1
			dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 0.5.7-BETA-build1
			dml-refabricated-rei: DML: Refabricated - REI Integration 0.5.7-BETA-build1
			ktdatataglib: KtDataTagLib 1.6.6
		doom: Doom Fabric 4.2.26
		doublejump: Double Jump Mod 1.0.1+mc1.19
		dragonloot: DragonLoot 1.1.2
		duckling: Duckling 2.0.8
		dummmmmmy: MmmMmmMmmMmm 1.19-1.5.3
		dungeons_arise: When Dungeons Arise 2.1.54
		earthtojavamobs: Earth2Java 1.9.3
		eldritch_mobs: EldritchMobs 1.12.10
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			polymer: Polymer (Core) 0.2.18+1.19.2
				polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.0.3+1.19.2
			polymer-blocks-ext: Polymer Blocks 0.1.0-alpha.9+1.19.2
			server_translations_api: Server Translations API 1.4.18+1.19.2
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
		emojiful: Emojiful 4.0.4
			com_esotericsoftware_yamlbeans_yamlbeans: yamlbeans 1.15
		emotecraft: Emotecraft 2.2.7-b.build.47
		expandedstorage: Expanded Storage 8.1.0-beta.3
		experiencebugfix: Experience Bug Fix 18
		explorerscompass: Explorer's Compass 1.19.2-2.2.0-fabric
		extended_drawers: Extended Drawers 1.3.5+mc.1.19.2
			graphlib: Graph Lib 0.3.1+1.19
			mconfig: Mconfig 1.2.0+mc.1.19-rc1
				de_poiu_apron_apron: apron 2.1.1
		extra_classes_origins: Extra Classes - Origins 1.0.0
		extragenerators: Extra Generators 1.2.1-BETA+1.19
		extrakeybinds: ThatRobins Extra Origins Keybinds 0.4.0+1.17-1.19.2
		extraorigins: Extra Origins 1.19-2
		fabric-api: Fabric API 0.71.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.14+6e0787e690
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.13+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.14+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.10+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.31+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.40+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.5+2d2baf4b90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.34+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.3+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.33+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.33+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.3+9785ec3590
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.37+9244241690
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.3+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.11+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.14+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.6+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.22+33fbc73890
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.10+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.27+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.5+9785ec3590
			fabric-particles-v1: Fabric Particles (v1) 1.0.13+4d0d570390
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.31+9244241690
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.18+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.10+4d0d570390
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.6+1cc24b1b90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.4+4d0d570390
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-diagonal-panes: Fabric Diagonal Panes 0.6.4
		fabric-furnaces: Fabric Furnaces 2.2.0-1.19.2
		fabric-language-kotlin: Fabric Language Kotlin 1.9.0+kotlin.1.8.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabricenchantments: Fabric Enchantments 0.9.0
		fabricloader: Fabric Loader 0.14.12
		fabricshieldlib: Fabric Shield Lib 1.6.1-1.19
		fabrictailor: Fabric Tailor 2.0.1
			config2brigadier: Config to Brigadier 1.2.1
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fallingtree: FallingTree 3.10.0
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		farmingforblockheads: Farming for Blockheads 11.1.0
		fastload: Fast Load 2.6.10
		ferritecore: FerriteCore 5.0.3
		flan: Flan 1.19.2-1.8.3
			rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		fluidtank: Fluid Tank 19.1.596-fabric
			org_typelevel_cats-core_2_13: cats-core_2.13 2.8.0
			org_typelevel_cats-kernel_2_13: cats-kernel_2.13 2.8.0
		forgeconfigapiport: Forge Config API Port 4.2.10
		frame: Frame 0.26.1+1.19-fabric
			frame-api-base: Frame Base 0.2.1+906ebc04a9
			frame-blocks-v0: Frame Blocks (v0) 0.1.3+233e7428a9
			frame-config-v0: Frame Config (v0) 0.3.1+0fa45150a9
			frame-content-registries-v0: Frame Content Registries (v0) 0.4.0+2876b511a9
			frame-enchantments-v0: Frame Enchantments (v0) 0.1.0+4093105da9
			frame-game-rules-v0: Frame Game Rules (v0) 0.2.4+e7ce56a6a9
			frame-items-v0: Frame Items (v0) 0.1.3+906ebc04a9
			frame-loot-tables-v0: Frame Loot Tables (v0) 0.1.4+4f7341eca9
			frame-registries-v0: Frame Registries (v0) 0.1.1+0e0ec74ea9
			frame-rendering-v0: Frame Rendering (v0) 0.1.5+906ebc04a9
			frame-tabbed-item-groups-v0: Frame Tabbed Item Groups (v0) 0.2.4+0aca9b56a9
			frame-toymaker-v0: Frame Data Generation Helpers (v0) 0.6.1+b13741c3a9
			frame-woods-v0: Frame Woods (v0) 0.2.1+6a33fbada9
		friendsandfoes: Friends&Foes 1.6.7
			com_github_llamalad7_mixinextras: MixinExtras 0.1.1
		ftblibrary: FTB Library 1902.3.11-build.166
		ftbquests: FTB Quests 1902.4.5-build.156
		ftbteams: FTB Teams 1902.2.11-build.87
		fwaystones: Fabric Waystones 3.0.5+mc1.19.2
		galosphere: Galosphere 1.19.2-1.2.1
		gearreborn: Gear Reborn 1.19-0.1.15
		geckolib3: Geckolib 3.1.38
			com_eliotlash_mclib_mclib: mclib 20
		genesis: Genesis 1.19.2-1.0.2
		givemehat: Give Me Hats! 2.5.0
		go-fish: Go Fish 1.6.0-1.19.1
		gobber2: Gobber2 2.6.61
			pugh_tools: Pugh Tools 1.3.23
		graveyard: The Graveyard 2.3
		graveyard_biomes: The Graveyard Biomes 1.6
		grounded_origins: Grounded Origins 1.2.3
			apugli: Apugli 1.9.3+1.19-fabric
		guardiansgalore: GuardiansGalore 1.19.2-3.0
		guardvillagers: Guard Villagers Fabric 1.19.2-1.0.16
		halfdoors: Half Doors 1.3.9+1.19.x
		harvest_scythes: Harvest Scythes 2.5.4+mc1.19.2
		hexcasting: Hex Casting 0.10.3
		hookshot: Hookshot 26.0
		horseinfo: Horse Info 0.4.2-1.19
		horsestatsvanilla: Horse Stats Vanilla 4.2.2
		iceberg: Iceberg 1.0.46
		immersive_aircraft: Immersive Aircraft 0.2.0+1.19.2
		impaled: Impaled 1.1.4
		impersonate: Impersonate 2.8.0
		incantationem: Incantationem 1.1.6+1.19
		indrev: Industrial Revolution 1.15.1-BETA
			libgui: LibGui 6.0.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		ingredient-extension-api: Ingredient Extension API 3.0.6
		inmis: Inmis 2.7.1-1.19
		itemfilters: Item Filters 1902.2.9-build.46
		jamlib: JamLib 0.6.0+1.19
		java: OpenJDK 64-Bit Server VM 17
		kibe: Kibe 1.9.10-BETA+1.19
		kjsextras: KubeJS Extras 3.0.0
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		kubejs: KubeJS 1902.6.0-build.135
		labels: labels 1.19.2-1.7
		lank: Lankasters Origins 1.0.0
		lavajava: Lava Java 0.4.1
		libra: Libra 0.5.44
		lightestlamp: Lightest Lamps 3.0.0f
		lilwings: Lil' Wings 1.2.3
		lithium: Lithium 0.10.4
		log_more_info: Log More Info 1.0.0-1.19
		logbegone: Log Begone 1.0.4
		logprot: Logprot Mod 1.19-1.9
		lootintegrations: Loot integration Mod 1.19.1-1.7
		lootjs: LootJS 2.7.8
		lovely_snails: Lovely Snails 1.1.0+1.19
		luggage: Luggage 1.19-1.5.2
			forge_tags: Porting Lib Tags 3.0
		macawsbridgesbyg: Macaw's Bridges - BYG 1.19.2-1.0
		marketcrates: Marketcrates 1.5
		mavapi: More Axolotl Variants API 1.0.1
		mavm: More Axolotl Variants Mod 1.2.0
		maxhealthfix: MaxHealthFix 8.0.1
		mcda: MC Dungeons Armors 2.2.0
		mcdar: MC Dungeons Artifacts 1.5.2-1.19
		mcdw: MC Dungeons Weapons 5.0.4-1.19
			enchant_giver: Enchant Giver 1.3.0
		mcpitanlibarch: MCPitanLibarch 1.3.5-1.19-fabric
		mcwbridges: Macaw's Bridges 1.0.6
		mcwfences: Macaw's Fences and Walls 1.0.7
		mcwlights: Macaw's Lights and Lamps 1.0.4
		mcwpaintings: Macaw's Paintings 1.0.4
		mcwwindows: Macaw's Windows 2.1.2
		megane: megane 8.3.0
			megane-alloy-forgery: megane-alloy-forgery 8.3.0
			megane-api: megane-api 8.3.0
			megane-applied-energistics-2: megane-applied-energistics-2 8.3.0
			megane-extra-generators: megane-extra-generators 8.3.0
			megane-fabric-transfer: megane-fabric-transfer 8.3.0
			megane-industrial-revolution: megane-industrial-revolution 8.3.0
			megane-kibe: megane-kibe 8.3.0
			megane-luggage: megane-luggage 8.3.0
			megane-modern-dynamics: megane-modern-dynamics 8.3.0
			megane-reborn-core: megane-reborn-core 8.3.0
			megane-reborn-energy: megane-reborn-energy 8.3.0
			megane-runtime: megane-runtime 8.3.0
			megane-tech-reborn: megane-tech-reborn 8.3.0
			megane-vanilla: megane-vanilla 8.3.0
			megane-wireless-networks: megane-wireless-networks 8.3.0
		megaparrot: Megaparrot 1.0.7-1.19.2
		midnightlib: MidnightLib 1.0.0
		milk_plus: Milk+ 4.0.44
		minecells: Mine Cells 1.3.3
		minecraft: Minecraft 1.19.2
		minepop: Mine Pop 0.0.1-1.19.2
		miningutility: Mining Utility 1.2.6+1.19
		mixintrace: MixinTrace 1.1.1+1.17
		mo_glass: Mo Glass 1.6.1-MC1.19.2
		mobz: MobZ 3.3.5
		mocolors: Mo' Colors 1.5.0
		modern_industrialization: Modern Industrialization 1.6.2-beta
			magna: Magna 1.8.0-1.19
		moderndynamics: Modern Dynamics 0.3.4-beta
		moonlight: Moonlight 1.19.2-2.1.26
		morebannerfeatures: More Banner Features 1.1.3
		morevillagers: More Villagers 4.0.2
		mtmechs: Magitek Mechs 1.0.14
		myloot: myLoot 3.1-1.19.2
		mythical_origins: Mythical Origins 1.0.0
		mythicmetals: Mythic Metals 0.16.4+1.19.2
		mythicmounts: Mythic Mounts 1.19.2-7.1
		naturescompass: Nature's Compass 1.19.2-2.1.0-fabric
		nyfsquiver: Nyf's Quivers Fabric-0.5.1-1.19.2
		omega-config: OmegaConfig 1.2.3-1.18.1
		onsoulfire: On Soul Fire 1.19-2
		origins: Origins 1.7.1
			apoli: Apoli 2.6.1
				calio: Calio 1.7.0
		origins-classes: Origins: Classes 1.4.0
		owo: oωo 0.9.3+1.19
			blue_endless_jankson: jankson 1.2.1
		paintings: Paintings++ 10.2.4.0
		patchouli: Patchouli 1.19.2-77-FABRIC
		patchoulibutton: PachouliButton 1.0.2
		paucal: PAUCAL 0.5.0
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.6.3+1.14.4-1.19.3
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		phosphor: Phosphor 0.8.1
		plantinajar: Plant In A Jar 2.5.0
			org_objenesis_objenesis: objenesis 3.2
		player-animator: Player Animator 0.4.0
		playerabilitylib: Pal 1.6.0
		plushies: Plushie Mod 1.2
		polymorph: Polymorph 0.46.1+1.19.2
			spectrelib: SpectreLib 0.11.0+1.19
		porting_lib: Porting Lib 2.1.706+1.19.2
			porting_lib_base: Porting Lib Base 2.1.706+1.19.2
				porting_lib_entity: Porting Lib Entity 2.1.706+1.19.2
				porting_lib_fake_players: Porting Lib Fake Players 2.1.706+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.706+1.19.2
			porting_lib_model_generators: Porting Lib Model Generators 2.1.706+1.19.2
				porting_lib_models: Porting Lib Models 2.1.706+1.19.2
					porting_lib_obj_loader: Porting Lib Obj Loader 2.1.706+1.19.2
						porting_lib_model_loader: Porting Lib Model Loader 2.1.706+1.19.2
					porting_lib_transfer: Porting Lib Transfer 2.1.706+1.19.2
						porting_lib_extensions: Porting Lib Extensions 2.1.706+1.19.2
							porting_lib_accessors: Porting Lib Accessors 2.1.706+1.19.2
							porting_lib_attributes: Porting Lib Attributes 2.1.706+1.19.2
								porting_lib_constants: Porting Lib Constants 2.1.706+1.19.2
							porting_lib_common: Porting Lib Common 2.1.706+1.19.2
			porting_lib_networking: Porting Lib Networking 2.1.706+1.19.2
		prefab: Prefab 4.2.4
		probejs: ProbeJS 4.2.1
		publicguiannouncement: Public Gui Announcement 4.3.3
		puzzleslib: Puzzles Lib 4.3.12
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		quarryplus: QuarryPlus 19.1.672
		questsadditions: Quests Additions 1.4.1
		quickhomes: QuickHomes 1.19.2-1.3.0
		quickshulker: Quick Shulker 1.3.9-1.19
			kyrptconfig: Kyrpt Config 1.4.16-1.19
			shulkerutils: shulkerutils 1.0.4-1.19
		reborncore: Reborn Core 5.4.0
			team_reborn_energy: Energy 2.3.0
		redbits: Red Bits 1.14.1
			interference: Interference API 1.4.2
		repurposed_structures: Repurposed Structures 6.1.3+1.19.2
		resourceful_tools: Resourceful Tools 1.3.26
			pugh_lib: Pugh Lib 1.4.15
		resourcefulconfig: Resourcefulconfig 1.0.18
		resourcefullib: Resourceful Lib 1.1.19
		respawnablepets: Respawnable Pets 1.19-2
		revelationary: Revelationary 1.1.0
		rhino: Rhino 1902.2.2-build.264
		rightclickharvest: Right Click Harvest 3.1.0+1.19-1.19.2
		rocks: This Rocks! 1.6.1
		rottencreatures: Rotten Creatures 1.0.1
		roughlyenoughitems: Roughly Enough Items 9.1.580
			error_notifier: Error Notifier 1.0.9
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		rpgstats: RPGStats 4.5.0+1.19.2
		sandwichable: Sandwichable 1.3.a+1.19
		shulkerboxtooltip: Shulker Box Tooltip 3.2.2+1.19.2
		silkspawners: SilkSpawners 1.1.2
		simplyswords: Simply Swords 1.37-1.19.2
		skylorlib: SkyLib 1.5.1
		spectrum: Spectrum 1.6.4-1.19.2-leisure_time
			additionalentityattributes: Additionalentityattributes 1.0.0+1.19
			arrowhead: Arrowhead 1.1.0-1.19.2
			incubus_core: Incubus Core 1.8.0
			programmerartinjector: Programmer Art Injector 1.2.1
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		spelunkery: Spelunkery 1.19.2-0.1.4
		spoornpacks: SpoornPacks 4.3.3-1.19.1
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.13.1
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.13.1
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.13.1
		spoornweaponattributes: SpoornWeaponAttributes 4.0.9-1.19
			net_objecthunter_exp4j: exp4j 0.4.8
		sprout: Sprout 1.4.4
		stoneholm: Stoneholm 1.4.4
		structory: Structory 1.0.1
		suggestion_tweaker: Suggestion Tweaker 1.19.1-1.3.1
		supplementaries: Supplementaries 1.19.2-2.2.35
		techreborn: Tech Reborn 5.4.0
		teenycoal: Teeny Coal 1.1.4-1.19.x
		tempad: Tempad 1.4.3
		terrablender: TerraBlender 2.0.1.136
		terralith: Terralith 2.3
		things: Things 0.2.20+1.19
		toms_storage: Tom's Simple Storage Mod 1.4.6
		toolstats: ToolStats 12.0.2
		totw_additions: Towers of the Wild: Additions 1.2.3
		tr-patchouli: Tech Reborn Patchouli 2.1.1
		tradingpost: Trading Post 4.2.0
		transparent: Transparent 5.1.2
		trashslot: TrashSlot 12.0.1
		travelersbackpack: Traveler's Backpack 1.19.2-8.2.10
		trinkets: Trinkets 3.4.1
		twigs: Twigs 2.0.0-beta.9+1.19-fabric
		vanityslots: Vanity Slots 1.2.5
		veinmining: Vein Mining 1.0.2+1.19.2
		villager-hats: Villager Hats 1.4.1
		villagerconfig: VillagerConfig 3.0.5-mc-1.19
		visualworkbench: Visual Workbench 4.2.1
		voidz: VoidZ 1.0.9
		voyager: Voyager v2 2.1.0-1.18-1.19.x
		walljump-fabric: Wall-Jump! UNOFFICIAL 1.6.1b
		wildlife: Wildlife 1.19.2-2.2
		winged: Winged Mod 1.19-3.3.0
		wirelessnetworks: Wireless Networks 1.6.0
		wthit: wthit 5.13.4
		xaerominimap: Xaero's Minimap 22.17.0
		xaeroworldmap: Xaero's World Map 1.28.7
		xps: Xp Obelisk 0.4.7-r+1.19.2-Fabric
		yigd: You're in Grave Danger 1.4.6
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.2
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
```

**Comment by micahflack** [comment]
In the meantime we've disabled the suspected blocks within the mod config

```
{
  "blocks": {
    ...
    "agave [default: true]": false,
    "barrel_cactus [default: true]": false,
    ...
    }
}
```
