### ISSUE TITLE
[Bug] Patchouli not working

### ISSUE THREAD

**Issue by Atmois** [quiqueck/BetterNether#164]
### What happened?

Patchouli fails to load due to seemimly a change which throws an error in the console, BetterEnd has the same issue seemimly. 

Bug report for the issue in BetterEnd here: 
https://github.com/quiqueck/BetterEnd/issues/287
https://github.com/quiqueck/BetterEnd/issues/278

This seems to outline how to fix it:
https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120

### BetterNether

9.0.9

### BCLib

3.0.13

### Fabric API

7.0.6+0.85.0-1.20.1 (QFAPI)

### Fabric Loader

0.19.3 (Quilt)

### Minecraft

1.20.1

### Relevant log output

```shell
[13:13:59] [Render thread/ERROR]: Failed to load book betternether:betternether_book defined by mod betternether, skipping
java.lang.IllegalArgumentException: Book betternether:betternether_book has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
	at vazkii.patchouli.common.book.Book.<init>(Book.java:145) ~[transformed-mod-patchouli.i0:0/:?]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[transformed-mod-patchouli.i0:0/:?]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[transformed-mod-patchouli.i0:0/:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[transformed-mod-patchouli.i0:0/:?]
	at vazkii.patchouli.fabric.common.FabricModInitializer.onInitialize(FabricModInitializer.java:33) ~[transformed-mod-patchouli.i0:0/:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:55) ~[quilt-loader-0.19.3.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36) ~[quilt-loader-0.19.3.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62) ~[quilt-loader-0.19.3.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49) ~[quilt-loader-0.19.3.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[quilt-loader-0.19.3.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:55) ~[quilt-loader-0.19.3.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:458) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[minecraft-1.20.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) ~[quilt-loader-0.19.3.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.19.3.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.19.3.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
```

### Other Mods

```shell
Patchouli 1.20.1-81
```

**Comment by milesomeat** [comment]
Still exists for Patchouli-1.20.1-84-FABRIC.jar

**Comment by HuntingForVodka** [comment]
Did some digging after I ran into the above error.
Also related issues tickets: #198 #200 

Unlike the BetterEnd fix there is no books to migrate for 1.20+ 
All that is currently is in place looks like place holder configuration inherited from pre fork  4 years ago https://github.com/quiqueck/BetterNether/blob/1.20.3/src/main/resources/data/betternether/patchouli_books/betternether_book/book.json
```
{
	"name": "BOOK NAME",
	"landing_text": "LANDING TEXT",
	"version": 1,
	"creative_tab": "betternether"
}
```
So to resolve this: 
remove support for Patchouli as no feature is currently implemented 
or 
Create content for the BetterNether guidebook and then updating as per 1.20+ assets requirements for Patchouli 
as detailed in https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 

for players and server operators no action is needed

**Comment by joeyfigaro** [comment]
See this PR for removing the unused patchouli resources: https://github.com/quiqueck/BetterNether/pull/266
