### ISSUE TITLE
[Bug] Ticking entity piglins

### ISSUE THREAD

**Issue by Sheepzor** [quiqueck/BetterNether#169]
### What happened?

Receiving ticking entity crashes in the nether specifically for piglins. Seems to happen when I enter the chunk of a piglin. Causes constant crashing when loading up the world. Tested in multiple worlds on multiple seeds on 9.08 and 9.09, happening in both versions. Not doing anything in particular, just when entering a new chunk.

### BetterNether

9.0.8

### BCLib

3.0.13

### Fabric API

0.83.0

### Fabric Loader

0.14.21

### Minecraft

1.20.0

### Relevant log output

```shell
Time: 2023-08-27 13:51:44
Description: Ticking entity

java.lang.ClassCastException: class net.minecraft.class_1739 cannot be cast to class com.autovw.advancednetherite.api.impl.IAdvancedHooks (net.minecraft.class_1739 and com.autovw.advancednetherite.api.impl.IAdvancedHooks are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @57175e74)
	at net.minecraft.class_4838.handler$zzd000$advancednetherite$isWearingGold(class_4838.java:986)
	at net.minecraft.class_4838.method_24719(class_4838.java)
	at net.minecraft.class_4834.method_19101(class_4834.java:94)
	at net.minecraft.class_4148.method_19100(class_4148.java:45)
	at net.minecraft.class_4095.method_27073(class_4095.java:498)
	at net.minecraft.class_4095.method_19542(class_4095.java:491)
	at net.minecraft.class_4836.method_5958(class_4836.java:335)
	at net.minecraft.class_1308.method_6023(class_1308.java:788)
	at net.minecraft.class_1309.method_6007(class_1309.java:2673)
	at net.minecraft.class_1308.method_6007(class_1308.java:550)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.minecraft.class_1309.method_5773(class_1309.java:2419)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_4838.handler$zzd000$advancednetherite$isWearingGold(class_4838.java:986)
	at net.minecraft.class_4838.method_24719(class_4838.java)
	at net.minecraft.class_4834.method_19101(class_4834.java:94)
	at net.minecraft.class_4148.method_19100(class_4148.java:45)
	at net.minecraft.class_4095.method_27073(class_4095.java:498)
	at net.minecraft.class_4095.method_19542(class_4095.java:491)
	at net.minecraft.class_4836.method_5958(class_4836.java:335)
	at net.minecraft.class_1308.method_6023(class_1308.java:788)
	at net.minecraft.class_1309.method_6007(class_1309.java:2673)
	at net.minecraft.class_1308.method_6007(class_1308.java:550)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.minecraft.class_1309.method_5773(class_1309.java:2419)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)

-- Entity being ticked --
Details:
	Entity Type: minecraft:piglin (net.minecraft.class_4836)
	Entity ID: 114
	Entity Name: Piglin
	Entity's Exact location: 76.20, 34.00, -16.70
	Entity's Block location: World: (76,34,-17), Section: (at 12,2,15 in 4,2,-2; chunk contains blocks 64,0,-32 to 79,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Sheepzorr'/110, l='ServerLevel[New World]', x=81.90, y=39.12, z=-11.20]]
	Chunk stats: 1089
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (112,64,11), Section: (at 0,0,11 in 7,4,0; chunk contains blocks 112,0,0 to 127,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1644 game time, 1644 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 66513 (now: false), thunder time: 157948 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Other Mods

```shell
3D Skin Layers 1.5.3
Advanced Netherite 2.0.1
Ambient Sounds 5.2.19
Better End 4.0.10
Better F3 7.0.0
Bushier Flowerrs 0.0.2
Collective 1.20.0-6.57
CreativeCore 2.10.23
Elytraslot 6.3.0
End portal recipe 1.20.0-5.0
Fabric API 0.83.0
Falling Leaves 1.15.0
Falling Tree 4.0.0
Infinite Trading 4.0
Iris 1.6.4
JEI 14.0.0.11
Modmenu 7.0.1
Mousetweaks 2.25
Nicer skies 1.2.0
Owo-lib 0.11.0
Presence footsteps 1.9.0
Sodium 1.20-0.4.10
Wraith Waystones 3.1.2
Xaeros Minimap 23.6.3
Xaeros Worldmap 1.33.1
```

**Comment by Fade-Alchemist** [comment]
I am also getting this
