### ISSUE TITLE
[Bug] Changing blocks config file causes startup crash.

### ISSUE THREAD

**Issue by GabFran** [quiqueck/BetterNether#171]
### What happened?

In a fresh Betternether install, without any other mods, changing any value in config/betternether/blocks.json from true to false causes startup crash. 

I found out this also happens when changing Better End's block config (config/betterend/blocks.json) 

The same does not occur, for example, when changing values in mobs.json.

### BetterNether

7.1.4

### BCLib

2.1.7

### Fabric API

0.76.1

### Fabric Loader

0.14.21 and 0.14.22

### Minecraft

1.19.2

### Relevant log output

```shell
[13:15:41] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.22
[13:15:41] [main/INFO]: Loading 56 mods:
	- bclib 2.1.7
	- betternether 7.1.4
	- fabric-api 0.76.1+1.19.2
	   |-- fabric-api-base 0.4.15+8f4e8eb390
	   |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
	   |-- fabric-biome-api-v1 9.1.1+16f1e31390
	   |-- fabric-block-api-v1 1.0.2+e415d50e90
	   |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
	   |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
	   |-- fabric-command-api-v1 1.2.16+f71b366f90
	   |-- fabric-command-api-v2 2.2.1+413cbbc790
	   |-- fabric-commands-v0 0.2.33+df3654b390
	   |-- fabric-containers-v0 0.1.42+df3654b390
	   |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
	   |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
	   |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
	   |-- fabric-data-generation-api-v1 5.3.9+413cbbc790
	   |-- fabric-dimensions-v1 2.1.35+0d0f210290
	   |-- fabric-entity-events-v1 1.5.4+9244241690
	   |-- fabric-events-interaction-v0 0.4.34+562bff6e90
	   |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
	   |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
	   |-- fabric-item-api-v1 1.6.6+b7d1888890
	   |-- fabric-item-groups-v0 0.3.39+9244241690
	   |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
	   |-- fabric-keybindings-v0 0.2.23+df3654b390
	   |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
	   |-- fabric-loot-api-v2 1.1.13+83a8659290
	   |-- fabric-loot-tables-v1 1.1.16+9e7660c690
	   |-- fabric-message-api-v1 5.0.7+93d8cb8290
	   |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
	   |-- fabric-models-v0 0.3.21+c6af733c90
	   |-- fabric-networking-api-v1 1.2.12+def3f86d90
	   |-- fabric-networking-v0 0.3.29+df3654b390
	   |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
	   |-- fabric-particles-v1 1.0.14+4d0d570390
	   |-- fabric-recipe-api-v1 1.0.2+413cbbc790
	   |-- fabric-registry-sync-v0 0.9.33+9244241690
	   |-- fabric-renderer-api-v1 1.2.1+1adbf27790
	   |-- fabric-renderer-indigo 0.8.0+1adbf27790
	   |-- fabric-renderer-registries-v1 3.2.24+df3654b390
	   |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
	   |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
	   |-- fabric-rendering-v0 1.1.27+df3654b390
	   |-- fabric-rendering-v1 1.12.1+d8ef690890
	   |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
	   |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
	   |-- fabric-screen-api-v1 1.0.32+4d0d570390
	   |-- fabric-screen-handler-api-v1 1.3.8+1cc24b1b90
	   |-- fabric-sound-api-v1 1.0.2+c4f28df590
	   |-- fabric-textures-v0 1.0.24+aeb40ebe90
	   |-- fabric-transfer-api-v1 2.1.6+413cbbc790
	   \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
	- fabricloader 0.14.22
	- java 17
	- minecraft 1.19.2
[13:15:41] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/gabfr/curseforge/minecraft/Install/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[13:15:41] [main/INFO]: Compatibility level set to JAVA_17
[13:15:43] [main/INFO]: [bclib] Added Config bclib.generator to auto sync (file hash)
[13:15:43] [main/INFO]: [bclib] Added Config bclib.main to auto sync (content diff)
[13:15:43] [main/INFO]: [bclib] Added Config bclib.recipes to auto sync (file hash)
[13:15:43] [main/INFO]: [bclib] Added Config bclib.biomes to auto sync (file hash)
[13:15:45] [main/INFO]: Building optimized datafixer
[13:15:49] [main/INFO]: [bclib] Added Config betternether.main to auto sync (file hash)
[13:15:49] [main/INFO]: [bclib] Added Config betternether.generator to auto sync (file hash)
[13:15:49] [main/INFO]: [bclib] Added Config betternether.blocks to auto sync (file hash)
[13:15:49] [main/INFO]: [bclib] Added Config betternether.items to auto sync (file hash)
[13:15:49] [main/INFO]: [bclib] Added Config betternether.biomes to auto sync (file hash)
[13:15:49] [main/INFO]: [bclib] Added Config betternether.mobs to auto sync (file hash)
[13:15:49] [main/INFO]: [bclib] Added Config betternether.recipes to auto sync (file hash)
[13:15:49] [main/WARN]: [bclib] Unable to build Recipe betternether:cincinnasite_sword
[13:15:49] [main/WARN]: [bclib] Unable to build Recipe betternether:cincinnasite_pickaxe
[13:15:49] [main/WARN]: [bclib] Unable to build Recipe betternether:cincinnasite_shovel
[13:15:49] [main/WARN]: [bclib] Unable to build Recipe betternether:cincinnasite_axe
[13:15:49] [main/WARN]: [bclib] Unable to build Recipe betternether:cincinnasite_hoe
[13:15:49] [main/WARN]: [bclib] Unable to build Recipe betternether:nether_ruby_sword
[13:15:49] [main/WARN]: [bclib] Unable to build Recipe betternether:nether_ruby_pickaxe
[13:15:49] [main/WARN]: [bclib] Unable to build Recipe betternether:nether_ruby_shovel
[13:15:49] [main/WARN]: [bclib] Unable to build Recipe betternether:nether_ruby_axe
[13:15:49] [main/WARN]: [bclib] Unable to build Recipe betternether:nether_ruby_hoe
[13:15:49] [main/WARN]: [bclib] Unable to build Recipe betternether:nether_reed_planks
[13:15:50] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:15:51] [Render thread/INFO]: Setting user: ~
[13:15:51] [Render thread/INFO]: [betternether] =^..^=    BetterNether for 1.19    =^..^=
[13:15:51] [Render thread/WARN]: [bclib] Unable to build Recipe betternether:paper
[13:15:51] [Render thread/WARN]: [bclib] Unable to build Recipe betternether:stick
[13:15:51] [Render thread/WARN]: [bclib] Unable to build Recipe betternether:sugar
[13:15:52] [Thread-1/INFO]: [bclib] Received Version Info for minecraft=1.19.2, loader=fabric
[13:15:52] [Thread-1/INFO]: [bclib]  - bclib:2.1.7
[13:15:52] [Thread-1/INFO]: [bclib]  - betternether:7.1.4
[13:15:52] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[13:15:52] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[13:15:55] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (BCLib, Better Nether, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric Block API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Client Tags, Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Recipe API (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Sound API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader)
[13:15:55] [Render thread/ERROR]: Unhandled game exception
java.lang.IllegalStateException: Some intrusive holders were not added to registry: [Reference{null=Block{minecraft:air}}]
	at net.minecraft.class_2370.method_40276(class_2370.java:352) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_40292(class_2378.java:404) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.handler$zll002$fabric-registry-sync-v0$onStart(class_310.java:5986) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:747) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.22.jar:?]
[13:15:55] [Render thread/INFO]: Stopping!
[13:15:56] [Render thread/ERROR]: Shutdown failure!
java.util.ConcurrentModificationException: null
	at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?]
	at net.minecraft.class_1060.close(class_1060.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.close(class_310.java:1092) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1490(class_310.java:1068) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:260) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.22.jar:?]
```

### Other Mods

```shell
none
```

**Comment by MacatMovie** [comment]
Same happens to me in 1.20.1, bclib-3.0.14, better nether 9.0.10.

**Comment by LividJava** [comment]
This happens when modifying the items.json file as well
