### ISSUE TITLE
[Bug] Failed to load datapacks

### ISSUE THREAD

**Issue by OcrSu** [quiqueck/BetterNether#192]
### What happened?

I'm troubleshooting a bug where my modpack client can't connect to the server. i found the following ERROR in the logs.
Hopefully the better nether dev team can fix it.
Log:https://mclo.gs/vfy6zG1

### BetterNether

9.0.10

### BCLib

3.0.14

### Fabric API

0.91.0

### Fabric Loader

0.15.6

### Minecraft

1.20.1

### Relevant log output

```shell
[10:18:21] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:209) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.6.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at org.betterx.betternether.items.NetherSword.putEnchantments(NetherSword.java:24) ~[better-nether-9.0.10.jar:?]
	at org.betterx.betternether.interfaces.InitialStackStateProvider.initializeState(InitialStackStateProvider.java:14) ~[better-nether-9.0.10.jar:?]
	at net.minecraft.class_1799.handler$zme000$betternether$bn_init(class_1799.java:2593) ~[server-intermediary.jar:?]
	at net.minecraft.class_1799.<init>(class_1799.java:175) ~[server-intermediary.jar:?]
	at net.minecraft.class_1799.<init>(class_1799.java:152) ~[server-intermediary.jar:?]
	at fzzyhmstrs.emi_loot.parser.LootTableParser.parseItemEntry(LootTableParser.java:379) ~[emi_loot-0.6.5+1.20.1.jar:?]
	at fzzyhmstrs.emi_loot.parser.LootTableParser.parseLootPoolEntry(LootTableParser.java:362) ~[emi_loot-0.6.5+1.20.1.jar:?]
	at fzzyhmstrs.emi_loot.parser.LootTableParser.parseLootPoolEntry(LootTableParser.java:355) ~[emi_loot-0.6.5+1.20.1.jar:?]
	at fzzyhmstrs.emi_loot.parser.LootTableParser.parseLootPoolEntry(LootTableParser.java:343) ~[emi_loot-0.6.5+1.20.1.jar:?]
	at fzzyhmstrs.emi_loot.parser.LootTableParser.parseChestLootTable(LootTableParser.java:209) ~[emi_loot-0.6.5+1.20.1.jar:?]
	at fzzyhmstrs.emi_loot.parser.LootTableParser.parseLootTable(LootTableParser.java:129) ~[emi_loot-0.6.5+1.20.1.jar:?]
	at fzzyhmstrs.emi_loot.parser.LootTableParser.lambda$parseLootTables$6(LootTableParser.java:102) ~[emi_loot-0.6.5+1.20.1.jar:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:292) ~[guava-31.1-jre.jar:?]
	at fzzyhmstrs.emi_loot.parser.LootTableParser.parseLootTables(LootTableParser.java:100) ~[emi_loot-0.6.5+1.20.1.jar:?]
	at net.minecraft.class_4014.mdc3e978$emi_loot$lambda$emi_loot_readTablesAfterFabricForRealSimple$0$0(class_4014.java:523) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:950) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	... 4 more
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:enchantment / betternether:obsidian_breaker])
	at net.minecraft.class_2370.method_40274(class_2370.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_46744(class_2370.java:141) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_39197(class_2378.java:118) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_10230(class_2378.java:114) ~[server-intermediary.jar:?]
	at org.betterx.betternether.registry.NetherEnchantments.register(NetherEnchantments.java:16) ~[better-nether-9.0.10.jar:?]
	at org.betterx.betternether.registry.NetherEnchantments.<clinit>(NetherEnchantments.java:12) ~[better-nether-9.0.10.jar:?]
	at org.betterx.betternether.items.NetherSword.putEnchantments(NetherSword.java:24) ~[better-nether-9.0.10.jar:?]
	at org.betterx.betternether.interfaces.InitialStackStateProvider.initializeState(InitialStackStateProvider.java:14) ~[better-nether-9.0.10.jar:?]
	at net.minecraft.class_1799.handler$zme000$betternether$bn_init(class_1799.java:2593) ~[server-intermediary.jar:?]
	at net.minecraft.class_1799.<init>(class_1799.java:175) ~[server-intermediary.jar:?]
	at net.minecraft.class_1799.<init>(class_1799.java:152) ~[server-intermediary.jar:?]
	at fzzyhmstrs.emi_loot.parser.LootTableParser.parseItemEntry(LootTableParser.java:379) ~[emi_loot-0.6.5+1.20.1.jar:?]
	at fzzyhmstrs.emi_loot.parser.LootTableParser.parseLootPoolEntry(LootTableParser.java:362) ~[emi_loot-0.6.5+1.20.1.jar:?]
	at fzzyhmstrs.emi_loot.parser.LootTableParser.parseLootPoolEntry(LootTableParser.java:355) ~[emi_loot-0.6.5+1.20.1.jar:?]
	at fzzyhmstrs.emi_loot.parser.LootTableParser.parseLootPoolEntry(LootTableParser.java:343) ~[emi_loot-0.6.5+1.20.1.jar:?]
	at fzzyhmstrs.emi_loot.parser.LootTableParser.parseChestLootTable(LootTableParser.java:209) ~[emi_loot-0.6.5+1.20.1.jar:?]
	at fzzyhmstrs.emi_loot.parser.LootTableParser.parseLootTable(LootTableParser.java:129) ~[emi_loot-0.6.5+1.20.1.jar:?]
	at fzzyhmstrs.emi_loot.parser.LootTableParser.lambda$parseLootTables$6(LootTableParser.java:102) ~[emi_loot-0.6.5+1.20.1.jar:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:292) ~[guava-31.1-jre.jar:?]
	at fzzyhmstrs.emi_loot.parser.LootTableParser.parseLootTables(LootTableParser.java:100) ~[emi_loot-0.6.5+1.20.1.jar:?]
	at net.minecraft.class_4014.mdc3e978$emi_loot$lambda$emi_loot_readTablesAfterFabricForRealSimple$0$0(class_4014.java:523) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:950) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	... 4 more
```

**Comment by OcrSu** [comment]
```
[10:18:13] [main/ERROR]: Failed to load book betternether:betternether_book defined by mod betternether, skipping
java.lang.IllegalArgumentException: Book betternether:betternether_book has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
	at vazkii.patchouli.common.book.Book.<init>(Book.java:145) ~[Patchouli-1.20.1-84-FABRIC.jar:?]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[Patchouli-1.20.1-84-FABRIC.jar:?]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[Patchouli-1.20.1-84-FABRIC.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[Patchouli-1.20.1-84-FABRIC.jar:?]
	at vazkii.patchouli.fabric.common.FabricModInitializer.onInitialize(FabricModInitializer.java:33) ~[Patchouli-1.20.1-84-FABRIC.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.6.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.6.jar:?]
```
