### ISSUE TITLE
[1.21] Incompatibility with Mythic Metals

### ISSUE THREAD

**Issue by Ollie434** [quiqueck/BetterNether#243]
### What happened?

Server crashed several times upon exploration of the nether, unsure what was being done to cause the crash. However in single player worlds having mythic metals enabled simply has you sit in the portal indefinitely and not enter at all. No crash log present for single player issue.

### BetterNether

21.0.5

### BCLib

21.0.5

### Fabric API

0.100.6

### Fabric Loader

0.15.11

### Minecraft

1.20.4

### Relevant log output

```shell
[21:44:04] [Worker-Main-3/WARN]: Failed to enumerate feature namespaces
java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:crimson_forest]=net.minecraft.class_1959@54d62358}, Reference{ResourceKey[minecraft:worldgen/biome / betternether:old_fungiwoods]=net.minecraft.class_1959@547f7c91}]
	at net.minecraft.class_7510.method_44210(class_7510.java:99) ~[server-intermediary.jar:?]
	at org.betterx.wover.biome.impl.modification.ChunkGeneratorHelper.lambda$rebuildFeaturesPerStep$2(ChunkGeneratorHelper.java:23) ~[wover-biome-21.0.6-b9f0c06855305370.jar:?]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181) ~[guava-32.1.2-jre.jar:?]
	at org.betterx.wover.generator.impl.chunkgenerator.ChunkGeneratorManagerImpl.enumerateFeatureNamespaces(ChunkGeneratorManagerImpl.java:124) ~[wover-generator-21.0.6-a556599aea299556.jar:?]
	at org.betterx.wover.generator.impl.chunkgenerator.ChunkGeneratorManagerImpl.printGeneratorInfo(ChunkGeneratorManagerImpl.java:190) ~[wover-generator-21.0.6-a556599aea299556.jar:?]
	at org.betterx.wover.generator.impl.chunkgenerator.WoverChunkGenerator.toString(WoverChunkGenerator.java:118) ~[wover-generator-21.0.6-a556599aea299556.jar:?]
	at net.minecraft.class_129$class_130.<init>(class_129.java:192) ~[server-intermediary.jar:?]
	at net.minecraft.class_129.method_578(class_129.java:92) ~[server-intermediary.jar:?]
	at net.minecraft.class_3898.method_60442(class_3898.java:643) ~[server-intermediary.jar:?]
	at net.minecraft.class_9761.method_60461(class_9761.java:96) ~[server-intermediary.jar:?]
	at net.minecraft.class_9759.method_60428(class_9759.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_9759.method_60427(class_9759.java:121) ~[server-intermediary.jar:?]
	at net.minecraft.class_9759.method_60432(class_9759.java:74) ~[server-intermediary.jar:?]
	at net.minecraft.class_9759.method_60424(class_9759.java:59) ~[server-intermediary.jar:?]
	at net.minecraft.class_3898.method_60446(class_3898.java:665) ~[server-intermediary.jar:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[server-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) [server-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) [server-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) [server-intermediary.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
[21:44:04] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for minecraft:the_nether
net.minecraft.class_148: Exception generating new chunk
	at net.minecraft.class_3898.method_60445(class_3898.java:647) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:552) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:561) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215.method_19492(class_3215.java:263) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:852) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:814) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:crimson_forest]=net.minecraft.class_1959@54d62358}, Reference{ResourceKey[minecraft:worldgen/biome / betternether:old_fungiwoods]=net.minecraft.class_1959@547f7c91}]
	at net.minecraft.class_7510.method_44210(class_7510.java:99) ~[server-intermediary.jar:?]
	at org.betterx.wover.biome.impl.modification.ChunkGeneratorHelper.lambda$rebuildFeaturesPerStep$2(ChunkGeneratorHelper.java:23) ~[wover-biome-21.0.6-b9f0c06855305370.jar:?]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181) ~[guava-32.1.2-jre.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:292) ~[server-intermediary.jar:?]
	at net.minecraft.class_9310.method_57610(class_9310.java:103) ~[server-intermediary.jar:?]
	at net.minecraft.class_9770.method_60560(class_9770.java:33) ~[server-intermediary.jar:?]
	at net.minecraft.class_3898.method_60442(class_3898.java:632) ~[server-intermediary.jar:?]
	at net.minecraft.class_9761.method_60461(class_9761.java:96) ~[server-intermediary.jar:?]
	at net.minecraft.class_9759.method_60428(class_9759.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_9759.method_60427(class_9759.java:121) ~[server-intermediary.jar:?]
	at net.minecraft.class_9759.method_60432(class_9759.java:74) ~[server-intermediary.jar:?]
	at net.minecraft.class_9759.method_60424(class_9759.java:59) ~[server-intermediary.jar:?]
	at net.minecraft.class_3898.method_60446(class_3898.java:665) ~[server-intermediary.jar:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[server-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[server-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[server-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[server-intermediary.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
[21:44:04] [Server thread/INFO]: Stopping server
```

### Other Mods

```shell
ImmediatelyFast
FabricSkyBoxes Interop
 Client Side Noteblocks
Complementary Shaders - Reimagined
Bosses of Mass Destruction
Cardinal Components API
Litematica
Boats On Lilypads
Enhanced Block Entities
Tool Trims
oωo (owo-lib)
YetAnotherConfigLib
Double Doors
Cull Leaves
disable front perspective
Paginated Advancements & Custom Frames
Reese's Sodium Options
Iris Shaders
Continuity
Geckolib
More Chat History
Distant Horizons
Dynamic FPS
Traveler's Backpack
Animatica
Lithium
Fabric API
BCLib
JJElytraSwap
M.R.U
Cubes Without Borders
Just Enough Items
Fast Better Grass
Translations for Sodium
FabricSkyboxes
Language Reload
Controlify
Horde Nights
Architectury API
Fast Minecart
Xaero's Minimap
Sodium
[EMF] Entity Model Features
Zoomify
OptiGUI
BetterF3
Explorify
No Chat Reports
Animal Feeding Trough
World Weaver
Let Me Despawn
Alloy Forgery
Capes
Cloth Config API
Mod Menu Helper.zip
Fabric Language Kotlin
FastQuit
Balm
[ETF] Entity Texture Features
Main Menu Credits
Model Gap Fix
Xaero's World Map
Mod Menu
Debugify
Sodium Extra
cat_jam
End Remastered
Fabrishot
Waystones
libIPN
MixinTrace
Stack to Nearby Chests
Polytone
e4mc
FerriteCore
Enchanting Tree
Eating Animation
Advanced Netherite
Inventory Profiles Next
BetterEnd
Chat Reporting Helper
Your Options Shall Be Respected (YOSBR)
Indium
Entity Culling
Replanter Plus
Snow Under Trees (Fabric)
Larger Ore Veins: Nether
Visuality
Mythic Metals
BetterNether
MaLiLib
ModernFix
Puzzle
Collective
```

**Comment by Noaaan** [comment]
Can confirm this happens in 1.21 as well, as seen in https://github.com/Noaaan/MythicMetals/issues/251

The feature order cycle seems to happen when adding a feature to the world with a new namespace. Lobger log provided:
https://github.com/user-attachments/files/16145057/latest.log

This should be easily reproducible and testable in-dev, as I add my features with Fabric APIs `BiomeModifications`. Using it should likely produce the same results

**Comment by muon-rw** [comment]
Looks to have been fixed with `bclib-21.0.8`

**Comment by Noaaan** [comment]
Can confirm, this issue can be closed
