### ISSUE TITLE
Exception Ticking World; Eye block

### ISSUE THREAD

**Issue by Arriochh** [quiqueck/BetterNether#33]
### What happened?

I was minding my own business just surviving in the nether when all of a sudden the server shutdown, and the eye block seems to be the culprit. 

java.lang.IllegalArgumentException: Cannot get property class_2758{name=level, clazz=class java.lang.Integer, values=[1, 2, 3]} as it does not exist in Block{minecraft:cauldron}

### BetterNether

6.1.2 (1.18.2 latest)

### BCLib

1.4.7 (1.18.2 latest)

### Fabric API

0.57.0

### Fabric Loader

0.14.8

### Minecraft

1.18.2

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Sorry :(

Time: 7/6/22, 6:46 AM
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot get property class_2758{name=level, clazz=class java.lang.Integer, values=[1, 2, 3]} as it does not exist in Block{minecraft:cauldron}
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at paulevs.betternether.blocks.BlockEyeball.method_9588(BlockEyeball.java:47)
	at net.minecraft.class_4970.method_9514(class_4970.java:363)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:923)
	at net.minecraft.class_3218.redirect$ben000$redirectBlockStateTick(class_3218.java:8171)
	at net.minecraft.class_3218.method_18203(class_3218.java:486)
	at net.minecraft.class_3215.method_14161(class_3215.java:378)
	at net.minecraft.class_3215.method_12127(class_3215.java:322)
	at net.minecraft.class_3218.method_18765(class_3218.java:311)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.class_3176.method_3813(class_3176.java:322)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at paulevs.betternether.blocks.BlockEyeball.method_9588(BlockEyeball.java:47)
	at net.minecraft.class_4970.method_9514(class_4970.java:363)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:923)
	at net.minecraft.class_3218.redirect$ben000$redirectBlockStateTick(class_3218.java:8171)
	at net.minecraft.class_3218.method_18203(class_3218.java:486)
	at net.minecraft.class_3215.method_14161(class_3215.java:378)
	at net.minecraft.class_3215.method_12127(class_3215.java:322)
	at net.minecraft.class_3218.method_18765(class_3218.java:311)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Arrioch'/4000, l='ServerLevel[world]', x=78.30, y=30.00, z=104.29]]
	Chunk stats: 2401
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (2,43,-102), Section: (at 2,11,10 in 0,2,-7; chunk contains blocks 0,0,-112 to 15,255,-97), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 3188281 game time, 1219 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 5832 (now: true), thunder time: 5832 (now: true)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.class_3176.method_3813(class_3176.java:322)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 3.10.0-1160.36.2.el7.x86_64
	Java Version: 17.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1356331320 bytes (1293 MiB) / 2793406464 bytes (2664 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 2
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3800X 8-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 81788.16
	Virtual memory used (MB): 91829.14
	Swap memory total (MB): 17405.99
	Swap memory used (MB): 47.95
	JVM Flags: 20 total; -Xmx4096M -Xms2662M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		adorn: Adorn 3.5.0+1.18.2
		adventurez: AdventureZ 1.4.11
		amplified-nether: Amplified Nether 1.1
		architectury: Architectury 4.5.76
		awesomedungeonnether: Awesome Dungeon Edition Nether 1.0.2
		bclib: BCLib 1.4.7
		betterend: Better End 1.1.1
		bettermending: Better Mending 1.2.0+1.18.2
			midnightlib: MidnightLib 0.4.4
		betternether: Better Nether 6.1.2
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.7-1.18.2
			maelstrom_library: Maelstrom Library 1.2.4-1.18.2
			multipart_entities: MultipartEntities 1.1.5-1.18.2
		cloth-config: Cloth Config v6 6.2.62
			cloth-basic-math: cloth-basic-math 0.6.1
		dark-enchanting: Dark Enchanting 1.0.0+1.18.2
			libgui: LibGui 5.4.0+1.18.2
				jankson: Jankson 4.0.0+j1.2.0
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
			omega-config: OmegaConfig 1.2.3-1.18.1
		dataattributes: Data Attributes 1.1.8
		dimores: DimensionalOres 1.0.2
		disenchanter: Disenchanter 0.1.6+1.18
		eldritch_mobs: Eldritch Mobs 1.11.0
		fabric: Fabric API 0.57.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.22+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.0+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.18+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.1+6c4e5d0960
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.22+e6b169eb60
			fabric-networking-v0: Fabric Networking (v0) 0.3.9+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.9+0d9ab37260
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.1+1f6558e860
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.7.3+kotlin.1.6.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.20
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		fabricenchantments: Fabric Enchantments 0.7.2
		fabricloader: Fabric Loader 0.14.8
		ftbchunks: FTB Chunks 1802.3.6-build.147
		ftblibrary: FTB Library 1802.3.6-build.123
		ftbquests: FTB Quests 1802.3.8-build.101
		ftbteams: FTB Teams 1802.2.6-build.51
		geckolib3: Geckolib 3.0.50
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		hookshot: Hookshot 25.0
		itemfilters: Item Filters 1802.2.7-build.29
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.1.9
			com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		libraryferret: Library Ferret 1.0.3
		lithium: Lithium 0.7.10
		magiccombatwands: Magic Combat Wands 1.0.2
		medievalweapons: Medieval Weapons 1.2.0
			reach-entity-attributes: Reach Entity Attributes 2.1.1
		minecraft: Minecraft 1.18.2
		nameplate: Nameplate 1.0.2
		pandemonium: Requiem: Pandemonium 2.0.0-beta.8
			pandemoniumapi: Requiem: Pandemonium-API 2.0.0-beta.8
		phosphor: Phosphor 0.8.1
		physicsmod: Physics Mod 2.7.6
		playerex: PlayerEx 3.2.1
			cardinal-components-base: Cardinal Components API (base) 4.1.4
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
			net_objecthunter_exp4j: exp4j 0.4.8
			opc: Offline Player Cache 0.5.0
			placeholder-api: Placeholder API 1.1.3+1.17.1
		random_ring: Random Ring 1.0.20
		requiem: Requiem 2.0.0-beta.9
			automatone: Automatone 0.7.0
			blabber: Blabber 0.2.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.1.3
			cardinal-components-world: Cardinal Components API (worlds) 4.1.3
			chime: Chime 1.2.1
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			fiber: fiber 0.23.0-2
			impersonate: Impersonate 2.5.0
			locki: Locki 0.7.0
			playerabilitylib: Pal 1.5.0
			requiem-core: Requiem-Core 2.0.0-beta.9
			requiemapi: Requiem-API 2.0.0-beta.9
		rpgdifficulty: Rpg Difficulty 1.0.12
			cloth-api: Cloth API 3.2.64
				cloth-client-events-v0: Cloth Client Events v0 3.2.64
				cloth-common-events-v1: Cloth Common Events v1 3.2.64
				cloth-datagen-api-v1: Cloth Datagen v1 3.2.64
				cloth-utils-v1: Cloth Utils v1 3.2.64
		totw_additions: Towers of the Wild: Additions 1.2.1
		waystones: Waystones 2.5.4
		yigd: You're in Grave Danger 1.3.7
	Server Running: true
	Player Count: 1 / 100; [class_3222['Arrioch'/4000, l='ServerLevel[world]', x=78.30, y=30.00, z=104.29]]
	Data Packs: vanilla, Fabric Mods, file/ultris-v5-4-4a.zip
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

### Other Mods

```shell
Modpack:
- Adorn
- AdventureZ
- Amplified Nether
- Architectury (library)
- AwesomeDungeon Nether Edition
- BetterEnd
- BetterMending
- Bosses of Mass Destruction
- Cloth Config
- Dark Enchanting
- Data Attributes (library(?))
- Dimensional Ores
- Disenchanter
- Dynamic Sound Filters
- Eldritch Mobs
- Fabric Enchantments (last mod installed before crash, not sure)
- Fabric Language Kotlin
- FTB Library, Chunks, Teams, and Quests
- Geckolib (library)
- Hookshot
- Item Filters Fabric (dependency)
- LibraryFerret (library, obviously)
- Magic Combat Wands
- Medieval Weapons Fabric
- Nameplate
- Physics Mod
- PlayerEx
- RandomRing Fabric
- Requiem
- Requiem Pandemonium (addon)
- RPGdifficulty
- Towers of the Wild additions
- Wraith Waystones (dependency)
- You're in Grave Danger Fabric
```

**Comment by quiqueck** [comment]
Thanks for reporting. Do you have a cauldron placed under the eye?

**Comment by Arriochh** [comment]
Yup. I know there's only two eye-cauldron stations and its at the server's spawn. I removed them and the world is no longer ticking.

**Comment by Halloerik** [comment]
Hello, I got this issue too

[crash-2023-09-27_04.42.03-server.txt](https://github.com/quiqueck/BetterNether/files/12746847/crash-2023-09-27_04.42.03-server.txt)
