### ISSUE TITLE
[Bug] Weird crash with Better Villages

### ISSUE THREAD

**Issue by clmc99** [quiqueck/BetterNether#43]
### What happened?

Minecraft crashes on startup when both BetterNether and [Better Villages](https://www.curseforge.com/minecraft/mc-mods/better-village-fabric) (along with their respective dependencies) are in the mods folder, but only if BetterNether's blocks.json config file has been modified ([example that causes the crash](https://github.com/quiqueck/BetterNether/files/9191226/bv-bn.crash.txt)). I've tried changing both cincinnasite_chain and nether_lapis_ore to false from their defaults of true; both cause the crash. Expected behavior: Minecraft starts normally, and both villages and nether are better. 

### BetterNether

7.0.6

### BCLib

2.0.16

### Fabric API

0.58.0

### Fabric Loader

0.14.8

### Minecraft

1.19

### Relevant log output

```shell
[11:29:20] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
[11:29:20] [main/INFO]: Loading 55 mods:
	- bclib 2.0.16
	- betternether 7.0.6
	- bettervillage 1.0.2
	- fabric 0.58.0+1.19
	- fabric-api-base 0.4.9+e62f51a3a9 via fabric
	- fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
	- fabric-biome-api-v1 9.0.14+b2a4a624a9 via fabric
	- fabric-blockrenderlayer-v1 1.1.18+9ff28f40a9 via fabric
	- fabric-command-api-v1 1.2.6+f71b366fa9 via fabric
	- fabric-command-api-v2 2.1.2+0d55f585a9 via fabric
	- fabric-commands-v0 0.2.23+df3654b3a9 via fabric
	- fabric-containers-v0 0.1.28+df3654b3a9 via fabric
	- fabric-content-registries-v0 3.2.1+07df213ea9 via fabric
	- fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
	- fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
	- fabric-data-generation-api-v1 5.1.2+a680b9b4a9 via fabric
	- fabric-dimensions-v1 2.1.28+a6d2f785a9 via fabric
	- fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
	- fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
	- fabric-events-lifecycle-v0 0.2.26+df3654b3a9 via fabric
	- fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
	- fabric-item-api-v1 1.5.5+35a03c43a9 via fabric
	- fabric-item-groups-v0 0.3.26+9ff28f40a9 via fabric
	- fabric-key-binding-api-v1 1.0.18+9ff28f40a9 via fabric
	- fabric-keybindings-v0 0.2.16+df3654b3a9 via fabric
	- fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via fabric
	- fabric-loot-api-v2 1.1.1+03a4e568a9 via fabric
	- fabric-loot-tables-v1 1.1.4+9e7660c6a9 via fabric
	- fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
	- fabric-mining-level-api-v1 2.1.11+33fbc738a9 via fabric
	- fabric-models-v0 0.3.15+9ff28f40a9 via fabric
	- fabric-networking-api-v1 1.1.0+442de8b8a9 via fabric
	- fabric-networking-v0 0.3.15+df3654b3a9 via fabric
	- fabric-object-builder-api-v1 4.0.8+9ff28f40a9 via fabric
	- fabric-particles-v1 1.0.8+dc39553aa9 via fabric
	- fabric-registry-sync-v0 0.9.18+23c4cfefa9 via fabric
	- fabric-renderer-api-v1 1.0.8+9ff28f40a9 via fabric
	- fabric-renderer-indigo 0.6.10+5187d39fa9 via fabric
	- fabric-renderer-registries-v1 3.2.18+df3654b3a9 via fabric
	- fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
	- fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
	- fabric-rendering-v0 1.1.20+df3654b3a9 via fabric
	- fabric-rendering-v1 1.10.14+9ff28f40a9 via fabric
	- fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-resource-loader-v0 0.5.6+5f1a85e0a9 via fabric
	- fabric-screen-api-v1 1.0.24+f05effafa9 via fabric
	- fabric-screen-handler-api-v1 1.2.7+9ff28f40a9 via fabric
	- fabric-textures-v0 1.0.18+9ff28f40a9 via fabric
	- fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
	- fabricloader 0.14.8
	- java 17
	- libraryferret 2.0.0
	- minecraft 1.19
	- notenoughcrashes 4.1.6+1.19
[11:29:21] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/clmcm/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[11:29:21] [main/INFO]: Compatibility level set to JAVA_17
[11:29:22] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[11:29:22] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[11:29:24] [main/INFO]: [bclib] Added Config bclib.main to auto sync (content diff)
[11:29:24] [main/INFO]: [bclib] Added Config bclib.recipes to auto sync (file hash)
[11:29:26] [main/INFO]: Building optimized datafixer
[11:29:29] [main/INFO]: [bclib] Added Config betternether.main to auto sync (file hash)
[11:29:29] [main/INFO]: [bclib] Added Config betternether.generator to auto sync (file hash)
[11:29:29] [main/INFO]: [bclib] Added Config betternether.blocks to auto sync (file hash)
[11:29:29] [main/INFO]: [bclib] Added Config betternether.items to auto sync (file hash)
[11:29:29] [main/INFO]: [bclib] Added Config betternether.biomes to auto sync (file hash)
[11:29:29] [main/INFO]: [bclib] Added Config betternether.mobs to auto sync (file hash)
[11:29:29] [main/INFO]: [bclib] Added Config betternether.recipes to auto sync (file hash)
[11:29:31] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11:29:31] [Render thread/INFO]: Setting user: cheemspuff
[11:29:31] [Render thread/INFO]: [betternether] =^..^=    BetterNether for 1.19    =^..^=
[11:29:33] [Render thread/INFO]: [STDERR]: Failed to load properties
[11:29:33] [Render thread/INFO]: libraryferret - > Initialize library
[11:29:33] [Render thread/INFO]: libraryferret - > Initialized library
[11:29:34] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[11:29:34] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[11:29:37] [Render thread/WARN]: Removed resource pack continuity/default from options because it doesn't seem to exist anymore
[11:29:37] [Render thread/WARN]: Removed resource pack continuity/glass_pane_culling_fix from options because it doesn't seem to exist anymore
[11:29:39] [Render thread/INFO]: Narrator library for x64 successfully loaded
[11:29:40] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (BCLib, Better Nether, Better Village, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Library Ferret, Not Enough Crashes), LumiPBRCompat-v0.20.zip, VanillaTweaks_1.19.zip, JBI+Textures+1.14.4.zip, CamittaTweaks.zip, BetterEnd purpur.zip, DripstoneCustomTitle.zip, redwood.zip, infested-stone-resources-v1-3-0.zip, powdersnow.zip, chests-515-golden-trapped-chests.zip
[11:29:40] [Render thread/ERROR]: Unhandled game exception
java.lang.IllegalStateException: Some intrusive holders were not added to registry: [Reference{null=Block{minecraft:air}}]
	at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.9) ~[?:?]
	at net.minecraft.util.registry.SimpleRegistry.method_40276(SimpleRegistry:352) ~[?:?]
	at net.minecraft.util.registry.Registry.method_40292(Registry:404) ~[?:?]
	at net.minecraft.client.MinecraftClient.handler$zkn001$onStart(MinecraftClient:5903) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:713) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
[11:29:40] [Render thread/INFO]: Stopping!
[11:29:40] [Worker-Main-22/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/mangrove_propagule.json' in resourcepack: 'VanillaTweaks_1.19.zip' for variant: 'age=4,hanging=false': Overlapping definition with: age=4,stage=0,hanging=false
[11:29:40] [Worker-Main-22/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/mangrove_propagule.json' in resourcepack: 'VanillaTweaks_1.19.zip' for variant: 'age=4,hanging=false': Overlapping definition with: age=4,stage=0,hanging=false
[11:29:40] [Worker-Main-22/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/mangrove_propagule.json' in resourcepack: 'VanillaTweaks_1.19.zip' for variant: 'age=4,hanging=false': Overlapping definition with: age=4,stage=0,hanging=false
[11:29:40] [Worker-Main-22/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/mangrove_propagule.json' in resourcepack: 'VanillaTweaks_1.19.zip' for variant: 'age=4,hanging=false': Overlapping definition with: age=4,stage=0,hanging=false
[11:29:40] [Worker-Main-22/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/mangrove_propagule.json' in resourcepack: 'VanillaTweaks_1.19.zip' for variant: 'age=4,hanging=false': Overlapping definition with: age=4,stage=0,hanging=false
[11:29:40] [Worker-Main-22/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/mangrove_propagule.json' in resourcepack: 'VanillaTweaks_1.19.zip' for variant: 'age=4,hanging=false': Overlapping definition with: age=4,stage=0,hanging=false
[11:29:40] [Worker-Main-22/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/mangrove_propagule.json' in resourcepack: 'VanillaTweaks_1.19.zip' for variant: 'age=4,hanging=false': Overlapping definition with: age=4,stage=0,hanging=false
[11:29:40] [Worker-Main-22/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/mangrove_propagule.json' in resourcepack: 'VanillaTweaks_1.19.zip' for variant: 'age=4,hanging=false': Overlapping definition with: age=4,stage=0,hanging=false
[11:29:41] [Worker-Main-22/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/mangrove_propagule.json' in resourcepack: 'VanillaTweaks_1.19.zip' for variant: 'age=4,hanging=false': Overlapping definition with: age=4,stage=0,hanging=false
[11:29:41] [Worker-Main-22/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/mangrove_propagule.json' in resourcepack: 'VanillaTweaks_1.19.zip' for variant: 'age=4,hanging=false': Overlapping definition with: age=4,stage=0,hanging=false
[11:29:41] [Worker-Main-22/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/mangrove_propagule.json' in resourcepack: 'VanillaTweaks_1.19.zip' for variant: 'age=4,hanging=false': Overlapping definition with: age=4,stage=0,hanging=false
[11:29:45] [Render thread/ERROR]: Shutdown failure!
java.util.ConcurrentModificationException: null
	at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.9) ~[?:?]
	at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?]
	at net.minecraft.client.texture.TextureManager.close(TextureManager:173) ~[?:?]
	at net.minecraft.client.MinecraftClient.close(MinecraftClient:1058) ~[?:?]
	at net.minecraft.client.MinecraftClient.stop(MinecraftClient:1034) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:253) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
```

### Other Mods

```shell
BetterVillage-Fabric-1.19-1.0.2.jar
fabric-api-0.58.0+1.19.jar
LibraryFerret-Fabric-1.19-2.0.0.jar
notenoughcrashes-4.1.6+1.19-fabric.jar
```

**Comment by quiqueck** [comment]
Disabling Blocks can be quite cumbersome :)

If you disable `nether_lapis_ore` you also need to disable everything that is directly or indirectly dependant on that Block. This include Loot Tables (Ore->Lapis Pile) and Features. Both can only be altered when creating a Datapack.

**Comment by clmc99** [comment]
I'll probably just make a resource pack for it then! I wanted to disable nether lapis ore because I thought it looked a bit out of place, but I don't think it's OP or anything.
