### ISSUE TITLE
[Bug]  I recently upgrade to 1.19.2 and this mod is the only one that hasn't worked for me, yet.

### ISSUE THREAD

**Issue by shawncouch88** [quiqueck/BetterNether#52]
### What happened?

Crashes before the game even starts up. Also it's version 1.19.2 but that's not listed below as an option.

### BetterNether

7.1.0

### BCLib

2.1.0

### Fabric API

0.60.0

### Fabric Loader

0.14.9

### Minecraft

1.19.1

### Relevant log output

```shell
[05:19:41] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.9
[05:19:41] [ForkJoinPool-1-worker-4/WARN]: Mod wands uses the version 2.6.3_release which isn't compatible with Loader's extended semantic version format (Could not parse version number component '3_release'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[05:19:41] [ForkJoinPool-1-worker-12/WARN]: The mod "dungeons_arise" contains invalid entries in its mod json:
- Unsupported root entry "credits" at line 12 column 12
[05:19:41] [ForkJoinPool-1-worker-5/WARN]: Mod xps uses the version 0.4.5.r_for_1.19.x_Fabric which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'r_for_1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[05:19:41] [main/INFO]: Loading 272 mods:
	- additionaladditions 5.0.2
	- additionalstructures 4.1.0
	- advancednetherite 1.6.4-1.19.2
	- airhop 4.2.0
	- animal_feeding_trough 1.0.3+1.19.2
	- antighost 1.19.1-fabric0.58.5-1.1.5
	- anvilrestoration-fabric 1.6
	- appleskin 2.4.1+mc1.19
	- architectury 6.2.43
	- artifacts 7.1.1+fabric
	- attributefix 17.1.2
	- axesareweapons 1.6.0
	- badpackets 0.2.0
	- balm-fabric 4.5.2+0
	- bclib 2.0.20
	- bedbenefits 9.1.2
	- betterbeacon 1.0.8
	- betterbeaconplacement-fabric 1.9
	- bettercontrols 1.2.3
	- betterf3 1.3.2
	- betternether 7.0.9
	- bettersafebed 4
	- betterthirdperson 1.8.1
	- blastingsand 1.19.2-11
	- blue_endless_jankson 1.2.1 via jankson
	- bookshelf 16.1.4
	- borderlessmining 1.1.5+1.19
	- cardinal-components 5.0.1
	- cardinal-components-base 5.0.1 via cardinal-components
	- cardinal-components-block 5.0.1 via cardinal-components
	- cardinal-components-chunk 5.0.1 via cardinal-components
	- cardinal-components-entity 5.0.1 via cardinal-components
	- cardinal-components-item 5.0.1 via cardinal-components
	- cardinal-components-level 5.0.1 via cardinal-components
	- cardinal-components-scoreboard 5.0.1 via cardinal-components
	- cardinal-components-world 5.0.1 via cardinal-components
	- cem 0.7.1
	- charmofundying 6.0.0+1.19.2
	- chunky 1.2.217
	- citresewn 1.1.1+1.19
	- citresewn-defaults 1.1.1+1.19 via citresewn
	- cleancut 1.19.2-5.1-fabric
	- clienttweaks 8.1.0
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 8.0.75
	- clumps 9.0.0+11
	- coat 1.0.0-beta.17+mc22w17a via completeconfig
	- collective-fabric 4.50
	- com_electronwill_night-config_core 3.6.5 via forgeconfigapiport
	- com_electronwill_night-config_toml 3.6.5 via forgeconfigapiport
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_github_llamalad7_mixinextras 0.0.12 via cull-less-leaves
	- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
	- com_typesafe_config 1.4.1 via croptopia
	- comforts 6.0.0+1.19.2
	- completeconfig 2.0.0
	- completeconfig-base 2.0.0 via completeconfig
	- completeconfig-gui-cloth 2.0.0 via completeconfig
	- completeconfig-gui-coat 2.0.0 via completeconfig
	- conditional-mixin 0.3.0 via cull-less-leaves
	- continuity 2.0.1+1.19
	- controlling 10.0+6
	- copper_pipe 1.11-b5
	- craftingpad 1.0.9
	- craftingtweaks 15.1.0
	- croptopia 2.1.0
	- crowdin-translate 1.4+1.19 via antighost
	- cull-less-leaves 1.0.5
	- customizableelytra 1.6.2-1.19
	- debugify 2.5.0
	- decorative_blocks 3.0.0
	- dev_isxander_settxi_settxi-core 2.7.4 via zoomify
	- dev_isxander_settxi_settxi-kotlinx-serialization 2.7.4 via zoomify
	- doodads 0.1.2-1.19.2
	- duckling 2.0.6
	- dungeons_arise 2.1.51
	- dynview 1.19.1-2.3
	- easymagic 4.3.2
	- economical_villager_trading 1.2.8
	- elytraslot 6.0.0+1.19.2
	- enchantinginfuser 4.2.0
	- enchdesc 13.0.1
	- enhanced_attack_indicator 1.0.4+1.19
	- entityculling 1.5.2-mc1.19
	- error_notifier 1.0.9 via roughlyenoughitems
	- expandability 6.0.0 via artifacts
	- extensibleenums 4.0.0 via universalenchants
	- fabric-api 0.60.0+1.19.2
	- fabric-api-base 0.4.11+e62f51a390 via fabric-api
	- fabric-api-lookup-api-v1 1.6.9+9ff28f4090 via fabric-api
	- fabric-biome-api-v1 9.0.17+aeb40ebe90 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.20+aeb40ebe90 via fabric-api
	- fabric-client-tags-api-v1 1.0.1+b35fea8390 via fabric-api
	- fabric-command-api-v1 1.2.11+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.1.7+0c17ea9690 via fabric-api
	- fabric-commands-v0 0.2.28+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.34+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.2.3+aeb40ebe90 via fabric-api
	- fabric-convention-tags-v1 1.1.1+7cd20a1490 via fabric-api
	- fabric-crash-report-info-v1 0.2.5+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.1.8+a680b9b490 via fabric-api
	- fabric-dimensions-v1 2.1.30+aeb40ebe90 via fabric-api
	- fabric-entity-events-v1 1.4.18+9ff28f4090 via fabric-api
	- fabric-events-interaction-v0 0.4.28+aeb40ebe90 via fabric-api
	- fabric-events-lifecycle-v0 0.2.28+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.21+aeb40ebe90 via fabric-api
	- fabric-item-api-v1 1.5.7+35a03c4390 via fabric-api
	- fabric-item-groups-v0 0.3.28+aeb40ebe90 via fabric-api
	- fabric-key-binding-api-v1 1.0.20+aeb40ebe90 via fabric-api
	- fabric-keybindings-v0 0.2.18+df3654b390 via fabric-api
	- fabric-language-kotlin 1.8.3+kotlin.1.7.10
	- fabric-lifecycle-events-v1 2.1.2+aeb40ebe90 via fabric-api
	- fabric-loot-api-v2 1.1.3+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.6+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.3+176380a290 via fabric-api
	- fabric-mining-level-api-v1 2.1.14+33fbc73890 via fabric-api
	- fabric-models-v0 0.3.17+aeb40ebe90 via fabric-api
	- fabric-networking-api-v1 1.2.4+5eb68ef290 via fabric-api
	- fabric-networking-v0 0.3.21+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.0.11+aeb40ebe90 via fabric-api
	- fabric-particles-v1 1.0.10+aeb40ebe90 via fabric-api
	- fabric-registry-sync-v0 0.9.24+aeb40ebe90 via fabric-api
	- fabric-renderer-api-v1 1.0.10+aeb40ebe90 via fabric-api
	- fabric-renderer-indigo 0.6.12+aeb40ebe90 via fabric-api
	- fabric-renderer-registries-v1 3.2.20+df3654b390 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.14+aeb40ebe90 via fabric-api
	- fabric-rendering-fluids-v1 3.0.7+aeb40ebe90 via fabric-api
	- fabric-rendering-v0 1.1.22+df3654b390 via fabric-api
	- fabric-rendering-v1 1.10.16+aeb40ebe90 via fabric-api
	- fabric-resource-conditions-api-v1 2.0.11+e62f51a390 via fabric-api
	- fabric-resource-loader-v0 0.6.1+aeb40ebe90 via fabric-api
	- fabric-screen-api-v1 1.0.26+f05effaf90 via fabric-api
	- fabric-screen-handler-api-v1 1.2.13+9ff28f4090 via fabric-api
	- fabric-textures-v0 1.0.20+aeb40ebe90 via fabric-api
	- fabric-transfer-api-v1 2.0.11+83a8659290 via fabric-api
	- fabric-transitive-access-wideners-v1 1.3.0+42d99c3290 via fabric-api
	- fabricloader 0.14.9
	- fallingtree 3.9.2
	- farmersdelight 1.19-1.3.3
	- fastertools 1.4.0-1.19.1
	- fiber 0.23.0-2 via collective-fabric
	- forgeconfigapiport 4.2.3
	- friendlyfire 14.0.1
	- friendsandfoes 1.5.6
	- fwaystones 3.0.3+mc1.19.2
	- geckolib3 3.1.17
	- gravelminer 13.0.0
	- highlighter 1.1.4
	- hoetweaks-fabric 1.8
	- hopobetterruinedportal 1.3.1
	- iceberg 1.0.46
	- immersive_armors 1.4.2
	- indium 1.0.7+mc1.19
	- instantblocks 1.6.5
	- inventorio 1.8.3
	- inventoryhud 3.4.2
	- inventorysorter 1.8.10-1.19
	- inventorytabs 0.8.1-1.19.x
	- inventorytotem-fabric 2.0
	- io_leangen_geantyref_geantyref 1.3.11 via croptopia
	- iris 1.2.6
	- ironchests 3.0.2
	- jade 8.0.0
	- jamlib 0.4.4
	- jankson 4.1.1+j1.2.1 via libgui
	- java 17
	- kirin 1.11.0 via presencefootsteps
	- kleeslabs 12.1.0
	- kyrptconfig 1.4.14-1.19 via inventorysorter
	- lambdynlights 2.1.2+1.19
	- libgui 6.0.0-beta.5+1.19-pre1 via additionaladditions
	- libninepatch 1.1.0 via libgui
	- lithium 0.8.3
	- magnumtorch 4.2.0
	- memoryleakfix 1.19.1-0.7.0
	- merchantmarkers 1.2.3
	- midashunger 2.1.0+1.19.0
	- midnightlib 0.6.0
	- minecraft 1.19.2
	- mixin-conflict-helper 1.2.0
	- mixintrace 1.1.1+1.17
	- mm 2.3 via wilderwild
	- mob_catcher 1.2.8
	- mobscarecrow 2.2.1-1.19.1
	- modmenu 4.0.6
	- moonlight 1.19.2-2.0.23
	- moreculling 1.19.1-0.10.0
	- morevillagers 4.0.2
	- mousetweaks 2.22
	- noenchantcap 2.1.2+1.19.x
	- notenoughcrashes 4.1.8+1.19.2
	- onsoulfire 1.19-2
	- optigui 1.1.1
	- org_anarres_jcpp 1.4.14 via iris
	- org_apache_commons_commons-text 1.9 via optigui
	- org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.0 via fabric-language-kotlin
	- org_joml_joml 1.10.4 via sodium
	- org_spongepowered_configurate-core 4.1.2 via croptopia
	- org_spongepowered_configurate-hocon 4.1.2 via croptopia
	- overpoweredmending 2.7.0
	- patchouli 1.19.2-76-FABRIC
	- pinlib 0.1.3+1.19 via fwaystones
	- polymorph 0.45.0+1.19.2
	- presencefootsteps 1.6.1
	- pride 1.1.2+1.19 via lambdynlights
	- probablychests 0.5.4-1.19.1
	- puzzleslib 4.2.4
	- recast-fabric 2.1
	- reinfbarrel 2.2.1+1.19
	- reinfcore 3.0.2+1.19 via reinfbarrel
	- reinfshulker 2.1.1+1.19
	- replantingcrops-fabric 3.1
	- repurposed_structures 6.1.1+1.19
	- rightclickharvest 3.0.1
	- roughlyenoughitems 9.1.530
	- roughlyenoughresources 2.6.0
	- rpgdifficulty 1.2.1
	- saplanting 1.1.3+1
	- seasons 1.4-BETA+1.19
	- sentimentality3 1.5.0
	- settxi-gui-cloth-config 2.7.4 via zoomify
	- shulkerboxslot 5.0.0-beta.1+1.19.2
	- simplechunkloader 1.0.3
	- skylorlib 1.5.1
	- sodium 0.4.2+build.16
	- spawnermod 1.2.0
	- spectrelib 0.8.1+1.19 via comforts
	- spruceui 4.0.0+1.19 via lambdynlights
	- stacc 1.3.4 via stacker
	- stacker 3.0.2-1.19.x
	- stackrefill-fabric 2.6
	- starlight 1.1.1+fabric.ae22326
	- step-height-entity-attribute 1.0.0 via artifacts
	- steves_vanilla 1.19.2+2.0.0
	- structory 1.0.1
	- stylisheffects 4.3.0
	- sulfurpotassiummod 1.1.2
	- supplementaries 1.19.2-2.0.15
	- toolstats 12.0.2
	- tooltiptweaks 1.1.0
	- trade_cycling 1.19.2-1.0.5
	- tradingpost 4.2.0
	- trinkets 3.4.0
	- universalbonemeal 4.2.0
	- universalenchants 4.2.1
	- unstructured 0.5.2+1.19.2
	- vanillatweaks 1.5.61
	- villagernames-fabric 4.0
	- visualworkbench 4.2.0
	- voidtotem 2.1.0
	- wands 2.6.3_release
	- wilderwild 1.0.5-Fabric+1.19.2
	- wmitaf 3.1.0
	- wooledboots 1.4
	- wooltweaks-fabric 2.1
	- xaerominimap 22.13.2
	- xaeroworldmap 1.26.6
	- xps 0.4.5.r_for_1.19.x_Fabric
	- xtraarrows 2.0
	- yigd 1.4.2
	- zoomify 2.4.2
[05:19:42] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/manyf/curseforge/minecraft/Install/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[05:19:42] [main/INFO]: Compatibility level set to JAVA_16
[05:19:42] [main/INFO]: Compatibility level set to JAVA_17
[05:19:42] [main/WARN]: Reference map 'blastingsand-refmap.json' for blastingsand.mixins.json could not be read. If this is a development environment you can ignore this message
[05:19:42] [main/INFO]: Preloading Debugify
[05:19:42] [main/INFO]: Done.
[05:19:43] [main/INFO]: Loaded configuration file for Lithium: 94 options available, 0 override(s) found
[05:19:43] [main/WARN]: Reference map 'morevillagers-fabric-fabric-refmap.json' for morevillagers.mixins.json could not be read. If this is a development environment you can ignore this message
[05:19:43] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[05:19:43] [main/WARN]: Reference map 'sulfurpotassiummod-refmap.json' for sulfurpotassiummod.mixins.json could not be read. If this is a development environment you can ignore this message
[05:19:43] [main/WARN]: Reference map 'BuildingWands_mc1.19.2-fabric-refmap.json' for wands.mixins.json could not be read. If this is a development environment you can ignore this message
[05:19:43] [main/WARN]: Reference map 'xtraarrows-refmap.json' for xtraarrows.mixins.json could not be read. If this is a development environment you can ignore this message
[05:19:43] [main/WARN]: Error loading class: io/github/apace100/apoli/power/factory/condition/ConditionFactory (java.lang.ClassNotFoundException: io/github/apace100/apoli/power/factory/condition/ConditionFactory)
[05:19:43] [main/WARN]: @Mixin target io.github.apace100.apoli.power.factory.condition.ConditionFactory was not found mixins.artifacts.json:compat.origins.ConditionFactoryAccessor from mod artifacts
[05:19:43] [main/WARN]: Force disabled MC-228976 because it's conflicting with: lithium
[05:19:44] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[05:19:44] [main/WARN]: Error loading class: draylar/magna/api/MagnaTool (java.lang.ClassNotFoundException: draylar/magna/api/MagnaTool)
[05:19:46] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[05:19:46] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[05:19:48] [main/WARN]: @Final field field_6248:Lnet/minecraft/class_2371; in wooledboots.mixins.json:LivingEntityEdits from mod wooledboots should be final
[05:19:48] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=2 on vanillatweaks.mixins.json:events.MixinLivingEntity from mod vanillatweaks::handler$fce000$entityEquip exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[05:19:49] [main/INFO]: [bclib] Added Config bclib.generator to auto sync (file hash)
[05:19:49] [main/INFO]: [bclib] Added Config bclib.main to auto sync (content diff)
[05:19:49] [main/INFO]: [bclib] Added Config bclib.recipes to auto sync (file hash)
[05:19:49] [main/INFO]: [bclib] Added Config bclib.biomes to auto sync (file hash)
[05:19:51] [main/INFO]: Building optimized datafixer
[05:19:58] [main/INFO]: [bclib] Added Config betternether.main to auto sync (file hash)
[05:19:58] [main/INFO]: [bclib] Added Config betternether.generator to auto sync (file hash)
[05:19:58] [main/INFO]: [bclib] Added Config betternether.blocks to auto sync (file hash)
[05:19:58] [main/INFO]: [bclib] Added Config betternether.items to auto sync (file hash)
[05:19:58] [main/INFO]: [bclib] Added Config betternether.biomes to auto sync (file hash)
[05:19:58] [main/INFO]: [bclib] Added Config betternether.mobs to auto sync (file hash)
[05:19:58] [main/INFO]: [bclib] Added Config betternether.recipes to auto sync (file hash)
[05:19:59] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.8) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at org.betterx.betternether.registry.NetherBlocks.<clinit>(NetherBlocks.java:762) ~[better-nether-7.0.9.jar:?]
	at org.betterx.betternether.entity.EntityFirefly.<clinit>(EntityFirefly.java:549) ~[better-nether-7.0.9.jar:?]
	at org.betterx.betternether.registry.NetherEntities.<clinit>(NetherEntities.java:152) ~[better-nether-7.0.9.jar:?]
	at net.minecraft.entity.attribute.DefaultAttributeRegistry.handler$zpg000$hasDefinition(DefaultAttributeRegistry:531) ~[?:?]
	at net.minecraft.entity.attribute.DefaultAttributeRegistry.hasDefinitionFor(DefaultAttributeRegistry) ~[?:?]
	at net.minecraft.entity.attribute.DefaultAttributeRegistry.method_26876(DefaultAttributeRegistry:176) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.entity.attribute.DefaultAttributeRegistry.checkMissing(DefaultAttributeRegistry:178) ~[?:?]
	at net.minecraft.Bootstrap.logMissing(Bootstrap:136) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:162) ~[fabric-loader-0.14.9-1.19.2.jar:?]
	at net.minecraft.client.main.Main.main(Main:51) ~[fabric-loader-0.14.9-1.19.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 2 more
Caused by: java.lang.IllegalStateException: Feature configuration for betternether:temp_patch_twisting_vine can not be null!
	at org.betterx.bclib.api.v3.levelgen.features.BCLFeatureBuilder.buildAndRegister(BCLFeatureBuilder.java:226) ~[bclib-2.0.20.jar:?]
	at org.betterx.bclib.api.v3.levelgen.features.BCLFeatureBuilder.build(BCLFeatureBuilder.java:238) ~[bclib-2.0.20.jar:?]
	at org.betterx.bclib.api.v3.levelgen.features.BCLFeatureBuilder.inlinePlace(BCLFeatureBuilder.java:242) ~[bclib-2.0.20.jar:?]
	at org.betterx.betternether.registry.features.configured.NetherVines.<clinit>(NetherVines.java:113) ~[better-nether-7.0.9.jar:?]
	at org.betterx.betternether.registry.NetherBlocks.<clinit>(NetherBlocks.java:762) ~[better-nether-7.0.9.jar:?]
	at org.betterx.betternether.entity.EntityFirefly.<clinit>(EntityFirefly.java:549) ~[better-nether-7.0.9.jar:?]
	at org.betterx.betternether.registry.NetherEntities.<clinit>(NetherEntities.java:152) ~[better-nether-7.0.9.jar:?]
	at net.minecraft.entity.attribute.DefaultAttributeRegistry.handler$zpg000$hasDefinition(DefaultAttributeRegistry:531) ~[?:?]
	at net.minecraft.entity.attribute.DefaultAttributeRegistry.hasDefinitionFor(DefaultAttributeRegistry) ~[?:?]
	at net.minecraft.entity.attribute.DefaultAttributeRegistry.method_26876(DefaultAttributeRegistry:176) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.entity.attribute.DefaultAttributeRegistry.checkMissing(DefaultAttributeRegistry:178) ~[?:?]
	at net.minecraft.Bootstrap.logMissing(Bootstrap:136) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:162) ~[fabric-loader-0.14.9-1.19.2.jar:?]
	at net.minecraft.client.main.Main.main(Main:51) ~[fabric-loader-0.14.9-1.19.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 2 more
```

### Other Mods

```shell
They're all listed in the log output.
```

**Comment by xanthian** [comment]
wilderwild 1.0.5-Fabric+1.19.2 is incompatible , 
	 see #https://github.com/quiqueck/BetterNether/issues/48

**Comment by shawncouch88** [comment]
Oh! Thank you...that's so weird though, they don't effect the same
dimensions. .

**Comment by quiqueck** [comment]
Thanks for reporting. The log output states that BetterNether 7.0.9 is in use. Could you please try with the latest version of our mods and report back if this is still an issue for you?
