### ISSUE TITLE
Crash when Generating Nether - Mod Incompatibility? [Bug] 

### ISSUE THREAD

**Issue by lanwoodall423** [quiqueck/BetterNether#68]
### What happened?

Just added latest update of Better Nether, Better End, and BClib. Deleted DIM-1. Went to nether and server crashes. Tried 3x. 

### BetterNether

7.1.1

### BCLib

2.1.1

### Fabric API

0.62.0

### Fabric Loader

0.14.9

### Minecraft

1.19.2

### Relevant log output

```shell
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2022-10-11 19:29:52
Description: Watching Server

java.lang.Error: Watchdog
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.9)
	at java.lang.Thread.yield(Native Method)
	at net.minecraft.util.thread.ThreadExecutor.waitForTasks(ThreadExecutor:151)
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:142)
	at net.minecraft.server.world.ServerChunkManager.getChunkBlocking(ServerChunkManager:1781)
	at net.minecraft.server.world.ServerChunkManager.getChunk(ServerChunkManager:1677)
	at net.minecraft.world.World.getChunk(World:197)
	at net.minecraft.world.World.getChunk(World:5578)
	at net.minecraft.world.World.getBlockState(World:6070)
	at net.minecraft.world.WorldView.isAir(WorldView:98)
	at net.minecraft.world.PortalForcer.createPortal(PortalForcer:94)
	at net.minecraft.server.network.ServerPlayerEntity.getPortalRect(ServerPlayerEntity:833)
	at net.minecraft.entity.Entity.getTeleportTarget(Entity:2620)
	at net.minecraft.server.network.ServerPlayerEntity.getTeleportTarget(ServerPlayerEntity:731)
	at net.minecraft.server.network.ServerPlayerEntity.moveToWorld(ServerPlayerEntity:772)
	at net.minecraft.entity.Entity.tickPortal(Entity:2128)
	at net.minecraft.entity.Entity.baseTick(Entity:489)
	at net.minecraft.entity.LivingEntity.baseTick(LivingEntity:349)
	at net.minecraft.entity.Entity.tick(Entity:469)
	at net.minecraft.entity.LivingEntity.tick(LivingEntity:2346)
	at net.minecraft.entity.player.PlayerEntity.tick(PlayerEntity:284)
	at net.minecraft.server.network.ServerPlayerEntity.playerTick(ServerPlayerEntity:487)
	at net.minecraft.server.network.ServerPlayNetworkHandler.tick(ServerPlayNetworkHandler:268)
	at net.minecraft.network.ClientConnection.tick(ClientConnection:248)
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo:183)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:886)
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:289)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:819)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
	at net.minecraft.server.MinecraftServer$$Lambda$16368/0x0000000802b045d0.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at java.base@17.0.1/java.lang.Thread.yield(Native Method)
	at net.minecraft.class_1255.method_20813(class_1255.java:151)
	at net.minecraft.class_1255.method_18857(class_1255.java:142)
	at net.minecraft.class_3215.getChunkBlocking(class_3215.java:1781)
	at net.minecraft.class_3215.method_12121(class_3215.java:1677)
	at net.minecraft.class_1937.method_8402(class_1937.java:197)
	at net.minecraft.class_1937.method_8497(class_1937.java:5578)
	at net.minecraft.class_1937.method_8320(class_1937.java:6070)
	at net.minecraft.class_4538.method_22347(class_4538.java:98)
	at net.minecraft.class_1946.method_30482(class_1946.java:94)
	at net.minecraft.class_3222.method_30330(class_3222.java:833)
	at net.minecraft.class_1297.method_30329(class_1297.java:2620)
	at net.minecraft.class_3222.method_30329(class_3222.java:731)
	at net.minecraft.class_3222.method_5731(class_3222.java:772)
	at net.minecraft.class_1297.method_18379(class_1297.java:2128)
	at net.minecraft.class_1297.method_5670(class_1297.java:489)
	at net.minecraft.class_1309.method_5670(class_1309.java:349)
	at net.minecraft.class_1297.method_5773(class_1297.java:469)
	at net.minecraft.class_1309.method_5773(class_1309.java:2346)
	at net.minecraft.class_1657.method_5773(class_1657.java:284)
	at net.minecraft.class_3222.method_14226(class_3222.java:487)
	at net.minecraft.class_3244.method_18784(class_3244.java:268)
	at net.minecraft.class_2535.method_10754(class_2535.java:248)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)

Full Crashlog: https://hastebin.com/ubukafugoh.yaml
```

### Other Mods

```shell
additionaladditions: Additional Additions 5.1.0
		advanced_runtime_resource_pack: Runtime Resource Pack 0.6.4
		adventurez: AdventureZ 1.4.16
		almostunified: AlmostUnified 0.1.1
		alternate-current: Alternate Current 1.4.0
		amethyst_imbuement: Amethyst Imbuement 1.19-14
			amethyst_core: Amethyst Core 0.3.3+1.19
			playerabilitylib: Pal 1.6.0
			structurized-reborn: Structurized Reborn 1.19-01
		archeology: CapsLock Archeology Mod 0.2.4
		architectury: Architectury 6.2.46
		areas-fabric: Areas (Fabric) 3.2
		armorstatues: Armor Statues 4.0.0
		artifacts: Artifacts 7.1.1+fabric
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		attributefix: AttributeFix 17.1.2
		autotag-convention: AutoTag Convention 2.0.0+1.19
			autotag: AutoTag 2.0.0+1.19
		balm-fabric: Balm 4.5.2+0
		bambooeverything: Bamboo Everything 2.2.4-build.33+mc1.19.2
		bclib: BCLib 2.1.1
		betteranimalsplus: Better Animals Plus 1.19-11.0.7
		bettercombat: Better Combat 1.4.4+1.19
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.1.1
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.1.1
		betterend: Better End 2.1.1
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.1.2
		betternether: Better Nether 7.1.1
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.0
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.1.2
		bettertridents: Better Tridents 4.0.1
		betterwitchhuts: YUNG's Better Witch Huts 1.19.2-Fabric-2.0.1
		bewitchment: Bewitchment 1.19-5
			impersonate: Impersonate 2.7.0
		biomemakeover: Biome Makeover 1.19.2-1.5.12
		bisecthosting: BisectHosting 1.0.3
		blockrunner: Block Runner 4.2.0
		boat-with-everything: Boat with Everything 1.1.0
		bookshelf: Bookshelf 16.1.5
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.2-1.19
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		brewery: Brewery 0.2.0+1.19.2
			hologram-api: Hologram API 0.2.2+1.19
			more_codecs: More Codecs 0.2.2+1.18
			net_objecthunter_exp4j: exp4j 0.4.8
			polymer: Polymer (Core) 0.2.16+1.19.2
				polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.0.3+1.19.2
			sgui: sgui 1.1.5+1.19.1
		bwplus: Bewitchment Plus 1.19-5
			terraform-wood-api-v1: Terraform Wood API (v1) 4.1.1
		byg: Oh The Biomes You'll Go 2.0.0.12
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+11
		collective-fabric: Collective (Fabric) 5.4
		combatroll: Combat Roll 1.0.8+1.19
		connectiblechains: Connectible Chains 2.1.3+1.19.2
		cosmetic-armor: Cosmetic Armor 1.4.0
		creativecore: CreativeCore (Fabric) 2.8.5
		creaturesofthesnow: Creatures Of The Snow 3.1.0+1.19.2
		creeperoverhaul: Creeper Overhaul 2.0.3
		damagetilt: Damage Tilt 1.19-fabric-0.1.2
		dawn: Dawn API 3.5.0
		debugify: Debugify 2.7.1
			com_github_llamalad7_mixinextras: mixinextras 0.0.12
		decor4fabric: Decor4Fabric 1.2.1
		deeperdarker: Deeper And Darker 1.0.2b-fabric
			customportalapi: Custom Portal Api 0.0.1-beta52-1.19
		diagonalfences: Diagonal Fences 4.2.1
		discholder: Kenza's Disc Holder and DJ 1.3.0
			kirin: Kirin UI 1.11.0
			libgui: LibGui 6.0.1+1.19
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		display: Display 1.0.0
		display_case: Display Case Mod 1.0.3
		doodads: Doodads 0.1.2-1.19.2
		dynmap: Dynmap 3.4
		earthtojavamobs: Earth2Java 1.9.3
		easyanvils: Easy Anvils 4.0.1
		ecologics: Ecologics 2.1.10
		elden_horses: Elden Horses 1.0.1+1.19.2
		emotecraft: Emotecraft 2.2.5
		everycomp: Every Compat 1.19.2-2.0.4
		expandeddelight: Expanded Delight 0.2.2
		expert_armor: Expert_Armor 2.1.6
                farmersdelight: Farmer's Delight 1.19-1.3.3
		farmersknives: Farmer's Knives 2.1
		fastback: FastBack 0.4.0+1.19.2
fastload: Fast Load 1.2.0
		ferritecore: FerriteCore 4.2.1
		forgeconfigapiport: Forge Config API Port 4.2.6
		friendsandfoes: Friends&Foes 1.5.11
		geckolib3: Geckolib 3.1.22
			com_eliotlash_mclib_mclib: mclib 19
			com_eliotlash_molang_molang: molang 19
		geodes: More Geodes 1.5.1
		glow_ink_plus: Glow Ink Plus Mod 1.0.2-1.19.x
		go-fish: Go Fish 1.6.0-1.19.1
		goodall: Goodall 1.1.1
		graveyard: The Graveyard 2.0
			omega-config: OmegaConfig 1.2.2-1.18.1
		horsestatsvanilla: Horse Stats Vanilla 4.2.2
		iceberg: Iceberg 1.0.46
		impaled: Impaled 1.1.4
		incendium: Incendium + Seed Fix 5.1.0
		infinitybuttons: Infinity Buttons 2.0.0-mc1.19
		interactic: Interactic 0.1.11+1.19
		java: Java HotSpot(TM) 64-Bit Server VM 17
		kofitable: Kofi Table 1.0.4+1.19.x
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		letmedespawn: Let Me Despawn fabric-1.0.2
		lithium: Lithium 0.8.3
		lovely_snails: Lovely Snails 1.1.0+1.19
		map_atlases: Map Atlases 2.1.0
		mcwbridges: Macaw's Bridges 2.0.5
		mcwfences: Macaw's Fences and Walls 1.0.6
		mcwlights: Macaw's Lights and Lamps 1.0.4
		mcwpaintings: Macaw's Paintings 1.0.4
		mcwpaths: Macaw's Paths and Pavings 1.0.1
		mcwtrpdoors: Macaw's Trapdoors 1.0.7
		medievalweapons: Medieval Weapons 1.4.1
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		megaparrot: Megaparrot 1.0.7-1.19.2
		midnightlib: MidnightLib 0.6.1
		minecraft: Minecraft 1.19.2
		minelib: mine11lib 0.1.3+1.19
			com_sksamuel_scrimage_scrimage-core: scrimage-core 4.0.31
		mixintrace: MixinTrace 1.1.1+1.17
		mob_catcher: Mob Catcher 1.2.13
		mobscarecrow: Mob Scarecrow 2.2.1-1.19.1
		moonlight: Moonlight 1.19.2-2.0.32
		more-axolotls: More Axolotls 1.0.2
		more_babies: More Babies 1.0.0
		more_ladders: More Ladders fabric-1.0.1-1.19.2
		morediscs: More Music Discs 1.19.2-21
		morefrogs: More Frogs 1.19.x-1.2.3-fabric
		morevillagers: More Villagers 4.0.2
		naturalist: Naturalist 2.1.1
		nbtcrafting: NBT Crafting 2.2.1+mc1.19
		notenoughcrashes: Not Enough Crashes 4.1.8+1.19.2
		nox: Nox 2.0.0
		npcvariety: NPC Variety 2.2.2
		nullscape: Nullscape 1.2
		owo: oωo 0.8.4+1.19
			blue_endless_jankson: jankson 1.2.1
		patchouli: Patchouli 1.19.2-76-FABRIC
			fiber: fiber 0.23.0-2
		peculiarpieces: Peculiar Pieces 1.2.13+1.19.x
		pehkui: Pehkui 3.5.0+1.14.4-1.19.2
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		philips_ruins__fabric: Philips ruins 1.19.2 fabric 1.7
		pickyourpoison: Pick Your Poison 1.0.9
			org_json_json: json 20211205
		player-animator: Player Animator 0.3.5
		probablychests: Probably Chests 0.5.5-1.19.2
		puzzleslib: Puzzles Lib 4.3.9
		qu-enchantments: Qu Enchantments 1.2.4-1.19
		repurposed_structures: Repurposed Structures 6.1.1+1.19
		revelationary: Revelationary 1.0.2
		rocks: This Rocks! 1.6.1
		roughly_enough_loot_tables: Roughly Enough Loot Tables 1.19-1.0
		roughlyenoughitems: Roughly Enough Items 9.1.550
			error_notifier: Error Notifier 1.0.9
		roughlyenoughprofessions: Roughly Enough Professions 1.1.2
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		servercore: ServerCore 1.3.2-1.19.2
			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
			fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
			me_lucko_spark-api: spark-api 0.1-SNAPSHOT
			placeholder-api: Placeholder API 2.0.0-beta.7+1.19
		simple_shields: Simple Shields Mod 1.0.0 - 1.19
		skylorlib: SkyLib 1.5.1
		smoothboot: Smooth Boot 1.19-1.7.1
		snowyspirit: Snowy Spirit 1.19.2-2.0.7
		soulfired: Soul fire'd 1.1.0.0
		spark: spark 1.9.40
		spiderstpo: Spiders 2.0 2.0.1
		starlight: Starlight 1.1.1+fabric.ae22326
		steves_vanilla: Steves Vanilla 1.19.2+2.0.1
		stoneholm: Stoneholm 1.4.4
		strawgolem: Straw Golem 2.0.0b2
		structory: Structory 1.0.1
		supplementaries: Supplementaries 1.19.2-2.2.6
		t_and_t: Towns and Towers - Structure Add-on 1.8.2
		tenshilib: TenshiLib 1.19-1.6.10
		terrablender: TerraBlender 2.0.1.127
		terralith: Terralith 2.3
		the_bumblezone: The Bumblezone - Fabric 6.1.14+1.19.2
			fake-player-api: Fake Player API 0.4.0
		themissingvillages: BigReefer's The Missing Villages Mod 2.0.0
		things: Things 0.2.20+1.19
		transparent: Transparent 5.1.0
		transportables: Transportables 1.2.1
		trashslot: TrashSlot 12.0.1
		treechop: HT's TreeChop 0.16.1
		trinkets: Trinkets 3.4.0
		universal_ores: Universal Ores 1.4.2
		untitledduckmod: Untitled Duck Mod 0.6.1
		variant_bookshelves: Variant Bookshelves 1.2.0
		variant_grindstones: Variant Grindstones 1.1.0
		variantbarrels: Variant Barrels 2.3
		variantcomposters: Variant Composters 1.0.5
		variantcraftingtables: Variant Crafting Tables 3.2.6
		visiblebarriers: Visible Barriers 1.5.3+1.19.x
		visualworkbench: Visual Workbench 4.2.0
		voidz: VoidZ 1.0.9
		vsas: Variant Sticks and Stuff 2.1.7
		wabi_sabi_structures: Wabi-Sabi Structures 1.0.3
		weaponmaster: YDM's Weapon Master 3.0.2
		wilderwild: Wilder Wild 1.1.1-Fabric+1.19.2
			frozenblocklib: FrozenBlock's Library 1.1.1-Fabric+1.19.2
			mm: Manningham Mills 2.3
		windchimes: Windchimes 1.2.1
		xps: Xp Obelisk 0.4.6-r+1.19.2-Fabric
		xtraarrows: Xtra Arrows 2.0
		yungsapi: YUNG's API 1.19.2-Fabric-3.6.1
		yungsbridges: YUNG's Bridges 1.19.2-Fabric-3.0.1
		yungsextras: YUNG's Extras 1.19.2-Fabric-3.0.1
```

**Comment by quiqueck** [comment]
Thanks for reporting. 
Judging by the logs, BetterNether is not directly involved in the crash. Unfortunately I am also unable to reproduce this on my end. Could you please try again without *Servercore*.

**Comment by unilock** [comment]
I was having this issue too. Crash log: https://gist.github.com/unilock/6b3f1ee03ab927f640672db02b61aadd

In case anyone else has this problem, removing [Faster Random](https://modrinth.com/mod/faster-random) fixed it for me.
