### ISSUE TITLE
BetterNether Naga Crash ?

### ISSUE THREAD

**Issue by OmarE505** [quiqueck/BetterNether#73]
### What happened?

So i was just cruising through the nether and the moment i found the naga the server crashed , im playing on "medieval minecraft modpack 1.19.2 v9" and since that crash i can't join the game or the server crashes immediately

### BetterNether

7.1.1

### BCLib

2.1.2

### Fabric Loader

0.14.9

### Minecraft

1.19.2

### Relevant log output

```shell
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 2022-10-25 10:51:29
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5132.method_26864(net.minecraft.class_1320)" because the return value of "java.util.Map.get(Object)" is null
	at net.rpgdifficulty.api.MobStrengthener.changeAttributes(MobStrengthener.java:189)
	at net.minecraft.class_3218.handler$fjn000$spawnEntityMixin(class_3218.java:20215)
	at net.minecraft.class_3218.method_8649(class_3218.java)
	at org.betterx.betternether.entity.EntityNaga.method_7105(EntityNaga.java:60)
	at net.minecraft.class_1381.method_6268(class_1381.java:96)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:119)
	at net.minecraft.class_1355.method_6275(class_1355.java:110)
	at net.minecraft.class_1308.method_6023(class_1308.java:753)
	at net.minecraft.class_1309.method_6007(class_1309.java:2641)
	at net.minecraft.class_1308.method_6007(class_1308.java:553)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.minecraft.class_1309.method_5773(class_1309.java:2385)
	at net.minecraft.class_1308.method_5773(class_1308.java:353)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.rpgdifficulty.api.MobStrengthener.changeAttributes(MobStrengthener.java:189)
	at net.minecraft.class_3218.handler$fjn000$spawnEntityMixin(class_3218.java:20215)
	at net.minecraft.class_3218.method_8649(class_3218.java)
	at org.betterx.betternether.entity.EntityNaga.method_7105(EntityNaga.java:60)
	at net.minecraft.class_1381.method_6268(class_1381.java:96)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:119)
	at net.minecraft.class_1355.method_6275(class_1355.java:110)
	at net.minecraft.class_1308.method_6023(class_1308.java:753)
	at net.minecraft.class_1309.method_6007(class_1309.java:2641)
	at net.minecraft.class_1308.method_6007(class_1308.java:553)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.minecraft.class_1309.method_5773(class_1309.java:2385)
	at net.minecraft.class_1308.method_5773(class_1308.java:353)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
Mixins in Stacktrace: None found

-- Entity being ticked --
Details:
	Entity Type: betternether:naga (org.betterx.betternether.entity.EntityNaga)
	Entity ID: 886
	Entity Name: entity.betternether.naga
	Entity's Exact location: -507.31, 101.00, -44.44
	Entity's Block location: World: (-508,101,-45), Section: (at 4,5,3 in -32,6,-3; chunk contains blocks -512,0,-48 to -497,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
Mixins in Stacktrace: None found

-- Affected level --
Details:
	All players: 1 total; [class_3222['Pedscim'/857, l='ServerLevel[world]', x=-497.58, y=99.00, z=-39.49]]
	Chunk stats: 1050
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (0,83,0), Section: (at 0,3,0 in 0,5,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6263459 game time, 5539295 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 6821 (now: true), thunder time: 87009 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
Mixins in Stacktrace: None found

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 5.8.18-100.fc31.x86_64
	Java Version: 17.0.1, Red Hat, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Red Hat, Inc.
	Memory: 1850542208 bytes (1764 MiB) / 3682598912 bytes (3512 MiB) up to 7516192768 bytes (7168 MiB)
	CPUs: 96
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) Gold 6240R CPU @ 2.40GHz
	Identifier: Intel64 Family 6 Model 85 Stepping 7
	Microarchitecture: Cascade Lake
	Frequency (GHz): 2.40
	Number of physical packages: 2
	Number of physical CPUs: 48
	Number of logical CPUs: 96
	Graphics card #0 name: ASPEED Graphics Family
	Graphics card #0 vendor: ASPEED Technology, Inc. (0x1a03)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: 0x2000
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 1000010.88
	Virtual memory used (MB): 657083.81
	Swap memory total (MB): 492341.94
	Swap memory used (MB): 12783.43
	JVM Flags: 2 total; -Xms256M -Xmx7168M
	Fabric Mods: 
		additionalstructures: Additional Structures 4.1.0
		adorn: Adorn 3.6.1+1.19
		advanced_runtime_resource_pack: Runtime Resource Pack 0.6.4
		advdebug: Advancements Debug 2.3.0
		adventurez: AdventureZ 1.4.16
		alloy_forgery: Alloy Forgery 2.0.16+1.19
		amplifiednether: Amplified nether 1.2
		another_furniture: Another Furniture 2.1.2-1.19.2
		arcanus: Arcanus 1.30
		architects_palette: Architect's Palette Fabric 2.1.1
		architectury: Architectury 6.3.49
		archon: Archon 0.3.3
			omega-config: OmegaConfig 1.2.3-1.18.1
		attributefix: AttributeFix 17.1.2
		autotag-convention: AutoTag Convention 2.0.0+1.19
			autotag: AutoTag 2.0.0+1.19
		badpackets: Bad Packets 0.2.0
		balm-fabric: Balm 4.5.2+0
		barteringstation: Bartering Station 4.0.2
		bcc: BetterCompatibilityChecker 2.0.2-build.16+mc1.19.1
		bclib: BCLib 2.1.2
		besmirchment: Besmirchment 1.19-5
			playerabilitylib: Pal 1.6.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			terraform-wood-api-v1: Terraform Wood API (v1) 4.1.1
		bettercombat: Better Combat 1.4.4+1.19
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.1
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterend: Better End 2.1.1
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		betternether: Better Nether 7.1.1
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.0
		betterstats: Better Statistics Screen 1.4.3
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		betterwitchhuts: YUNG's Better Witch Huts 1.19.2-Fabric-2.1.0
		bewitchment: Bewitchment 1.19-5
			impersonate: Impersonate 2.7.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		bhmenu: BHMenu-Fabric 1.19-1.3
		biomemakeover: Biome Makeover 1.19.2-1.5.12
		bookshelf: Bookshelf 16.1.5
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.3-1.19.2
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		bountiful: Bountiful 3.0.0
		bwplus: Bewitchment Plus 1.19-5
		byg: Oh The Biomes You'll Go 2.0.0.13
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charmofundying: Charm of Undying 6.0.0+1.19.2
		chubbystuff: Chubby Stuff ChubbyStuff-2.0.0+1.19.2
		cinderscapes: Cinderscapes 3.0.3
			cinderscapes-common: Cinderscapes: Common 3.0.3
			cinderscapes-worldgen: Cinderscapes: World Generation 3.0.3
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 4.1.1
			terraform-shapes-api-v1: Terraform Shapes API (v1) 4.1.1
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v8 8.2.88
		clumps: Clumps 9.0.0+11
		collective-fabric: Collective (Fabric) 5.11
			fiber: fiber 0.23.0-2
		combatroll: Combat Roll 1.0.8+1.19
		conjuring: Conjuring 1.0.25+1.19
		cosmetic-armor: Cosmetic Armor 1.4.0
		crashbrander: CrashBrander 1.2.0
		crawl: Crawl 0.11.1
			mm: Manningham Mills 2.3
		creaturesofthesnow: Creatures Of The Snow 3.1.0+1.19.2
		ctov: ChoiceTheorem's Overhauled Villages 3.1.2
		darkpaintings: DarkPaintings 13.1.2
		dataattributes: Data Attributes 1.2.7
		dawn: Dawn API 3.5.0
		dcch: DCCH 1.2
		debugify: Debugify 2.7.1
		decorative_blocks: Decorative Blocks 3.0.0
		deeperdarker: Deeper And Darker 1.0.2b-fabric
			customportalapi: Custom Portal Api 0.0.1-beta52-1.19
		deepslatecutting: Deepslate Cutting 1.5.0
		dehydration: Dehydration 1.3.1
		dragonloot: DragonLoot 1.1.2
		duckling: Duckling 2.0.7
		dummmmmmy: MmmMmmMmmMmm 1.19-1.5.3
		dungeons_arise: When Dungeons Arise 2.1.51
		easyanvils: Easy Anvils 4.0.5
		easymagic: Easy Magic 4.3.2
		ecologics: Ecologics 2.1.10
		edenring: EdenRing 0.6.4
		eldritch_mobs: EldritchMobs 1.12.7
		elytraslot: Elytra Slot 6.0.0+1.19.2
		endgoblintraders: End Goblin Traders 1.5.1
		endrem: End Remastered 5.2.0
		enhancedcelestials: Enhanced Celestials 2.1.0.1
		environmentz: EnvironmentZ 1.3.3
		everycomp: Every Compat 1.19.2-2.0.10
		expandeddelight: Expanded Delight 0.2.2
		fabric-api: Fabric API 0.64.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.12+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.29+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.35+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.0+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.2+b598f4ac90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.19+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.29+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.32+70efcffe90
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.6+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.9+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.17+33fbc73890
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90
			fabric-networking-v0: Fabric Networking (v0) 0.3.22+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.14+93d8cb8290
			fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.15+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.0+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.7.2+70efcffe90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.5+kotlin.1.7.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.4
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.9
		fallingtree: FallingTree 3.10.0
		farmersdelight: Farmer's Delight 1.19-1.3.3
		farmersknives: Farmer's Knives 2.1
		farsight: Farsight Mod 1.19-2.1
		ferritecore: FerriteCore 4.2.1
		forgeconfigapiport: Forge Config API Port 4.2.6
		frame: Frame 0.26.1+1.19-fabric
			frame-api-base: Frame Base 0.2.1+906ebc04a9
			frame-blocks-v0: Frame Blocks (v0) 0.1.3+233e7428a9
			frame-config-v0: Frame Config (v0) 0.3.1+0fa45150a9
			frame-content-registries-v0: Frame Content Registries (v0) 0.4.0+2876b511a9
			frame-enchantments-v0: Frame Enchantments (v0) 0.1.0+4093105da9
			frame-game-rules-v0: Frame Game Rules (v0) 0.2.4+e7ce56a6a9
			frame-items-v0: Frame Items (v0) 0.1.3+906ebc04a9
			frame-loot-tables-v0: Frame Loot Tables (v0) 0.1.4+4f7341eca9
			frame-registries-v0: Frame Registries (v0) 0.1.1+0e0ec74ea9
			frame-rendering-v0: Frame Rendering (v0) 0.1.5+906ebc04a9
			frame-tabbed-item-groups-v0: Frame Tabbed Item Groups (v0) 0.2.4+0aca9b56a9
			frame-toymaker-v0: Frame Data Generation Helpers (v0) 0.6.1+b13741c3a9
			frame-woods-v0: Frame Woods (v0) 0.2.1+6a33fbada9
		friendsandfoes: Friends&Foes 1.5.11
		ftbbackups2: FTB Backups 2 1.0.14
		ftbchunks: FTB Chunks 1902.3.9-build.168
		ftblibrary: FTB Library 1902.3.9-build.144
		ftbquests: FTB Quests 1902.4.2-build.116
		ftbteams: FTB Teams 1902.2.9-build.61
		fwaystones: Fabric Waystones 3.0.5+mc1.19.2
		galosphere: Galosphere 1.19.1-1.1.2
		geckolib3: Geckolib 3.1.26
			com_eliotlash_mclib_mclib: mclib 19
			com_eliotlash_molang_molang: molang 19
		geodes: More Geodes 1.5.1
		go-fish: Go Fish 1.6.0-1.19.1
		goblintraders: Goblin Traders 1.5.2
		goodall: Goodall 1.1.1
		graveyard: The Graveyard 2.0
		graveyard_biomes: The Graveyard Biomes 1.2
		guardvillagers: Guard Villagers Fabric 1.19.2-1.0.16
		horseexpert: Horse Expert 4.0.0
		icarus: Icarus 1.13
		iceberg: Iceberg 1.0.46
		immersive_armors: Immersive Armors 1.4.2
		imst: Immersive structures 2.0.3
		ingredient-extension-api: Ingredient Extension API 3.0.5
		interactic: Interactic 0.1.11+1.19
		itemfilters: Item Filters 1902.2.9-build.41
		jade: Jade 8.2.1
		jamlib: JamLib 0.4.4
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.3.0.271
		jmi: JourneyMapIntegration 0.13-30
		journeymap: Journeymap 5.9.0beta2
			journeymap-api-fabric: JourneyMap API 1.19.1-1.9-fabric-SNAPSHOT
		kambrik: Kambrik 4.0-1.19.2
		kiwi: Kiwi Lib 8.1.2
		kleeslabs: KleeSlabs 12.1.0
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		leavesbegone: Leaves Be Gone 4.0.0
		lithium: Lithium 0.10.0
		magnumtorch: Magnum Torch 4.2.0
		mcda: MC Dungeons Armors 2.2.0
		mcdar: MC Dungeons Artifacts 1.5.2-1.19
		mcdw: MC Dungeons Weapons 5.0.4-1.19
			enchant_giver: Enchant Giver 1.3.0
		mcsa: MC Story Mode Armors 3.1.2+1.19
		medievalmusic: Medieval Music Mod 1.19-1.8
		medievalorigins: Medieval Origins 1.19.x-4.1.3
		medievalweapons: Medieval Weapons 1.4.1
		memoryleakfix: memory Leak Fix 1.19.1-0.7.0
		midnightlib: MidnightLib 0.6.1
		minecraft: Minecraft 1.19.2
		minelib: mine11lib 0.1.3+1.19
			com_sksamuel_scrimage_scrimage-core: scrimage-core 4.0.31
		mixintrace: MixinTrace 1.1.1+1.17
		moonlight: Moonlight 1.19.2-2.1.3
		mvs: Vanilla Structure Mod 2.5.9
		mythicmetals: Mythic Metals 0.16.2+1.19.2
		mythicmetals_decorations: Mythic Metals Decorations 0.4.1
		mythicmounts: Mythic Mounts 1.19.2-7.0
		mythicupgrades: Mythic Upgrades 1.2.1
		nameplate: Nameplate 1.0.9
		naturalist: Naturalist 2.1.1
		naturescompass: Nature's Compass 1.19.2-2.0.4-fabric
		nears: Nears 1.2.3
		netherdepthsupgrade: Nether Depths Upgrade 1.1.0
		netherportalfix: NetherPortalFix 10.0.0
		no-resource-pack-warnings: No Resource Pack Warnings 1.0.0
		nochatreports: No Chat Reports 1.19.2-v1.13.9
		onsoulfire: On Soul Fire 1.19-2
		origins: Origins 1.7.0
			apoli: Apoli 2.6.0
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
		owo: oωo 0.8.5+1.19
			blue_endless_jankson: jankson 1.2.1
		paintings: Paintings++ 10.2.1.0
		passablefoliage: Passable Foliage 1.19-fabric-5.0.2
		patchouli: Patchouli 1.19.2-76-FABRIC
		paxi: Paxi 1.19.2-Fabric-3.0
		pehkui: Pehkui 3.5.0+1.14.4-1.19.2
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		player-animator: Player Animator 0.4.0-test1
		playerex: PlayerEx 3.3.7
			net_objecthunter_exp4j: exp4j 0.4.8
			opc: Offline Player Cache 0.6.4
			placeholder-api: Placeholder API 2.0.0-beta.7+1.19
		polylib: PolyLib 1900.0.2-build.27
		polymorph: Polymorph 0.45.0+1.19.2
		probablychests: Probably Chests 0.5.5-1.19.2
		professions: Professions 1.0.2
			com_typesafe_config: config 1.4.1
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			octo-economy-api: Octo Economy API 1.1.0
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		puzzleslib: Puzzles Lib 4.3.12
		quartzelv: Quartz Elevator 2.1.5+1.19
		redmorestructure: Reds More Structures 1.0.4-1.19.2
		relicex: RelicEx 3.2.5
			armorrenderlib: Armor Render Lib 0.2.6
		repurposed_structures: Repurposed Structures 6.1.1+1.19
		rhino: Rhino 1902.2.1-build.242
		rightclickharvest: Right Click Harvest 3.0.1
		rocks: This Rocks! 1.6.1
		rottencreatures: Rotten Creatures 0.1.0
		rpg_origins: RPG Origins 1.2.2
		rpgdifficulty: Rpg Difficulty 1.3.0
		seasons: Fabric Seasons 1.4-BETA+1.19
		skyvillages: Sky Villages 1.0.2.1
		smoothchunk: Smooth chunk save Mod 1.19.1-2.0
		snowyspirit: Snowy Spirit 1.19.2-2.0.7
		sod: Sod 22.10.13
		soulsweapons: Marium's Soulslike Weaponry 0.9.5
		spark: spark 1.9.42
		starlight: Starlight 1.1.1+fabric.ae22326
		starterkit-fabric: Starter Kit (Fabric) 3.8
		stoneholm: Stoneholm 1.4.4
		strawgolem: Straw Golem 2.0.0b2
		structory: Structory 1.0.1
		supplementaries: Supplementaries 1.19.2-2.2.9
		t_and_t: Towns and Towers - Structure Add-on 1.8.2
		terrablender: TerraBlender 2.0.1.128
		terrestria: Terrestria 5.0.2
			terraform-config-api-v1: Terraform Config API (v1) 4.1.1
			terraform-dirt-api-v1: Terraform Dirt API (v1) 4.1.1
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 4.1.1
			terraform-tree-api-v1: Terraform Tree API (v1) 4.1.1
			terrestria-common: Terrestria: Common 5.0.2
			terrestria-worldgen: Terrestria: World Generation 5.0.2
		the_bumblezone: The Bumblezone - Fabric 6.1.14+1.19.2
			fake-player-api: Fake Player API 0.4.0
		things: Things 0.2.20+1.19
		thonkutil: ThonkUtil 2.15.4+1.19
			thonkutil-base: ThonkUtil Base 1.13.2+4a8c408a57
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.4.2+3eb2749857
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.1.2+8ff533c957
			thonkutil-legacy: ThonkUtil Legacy 1.1.2+5d4263f557
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.1.3+bd4b387957
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.5.2+8ff533c957
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.2.2+8ff533c957
		tinyskeletons: Tiny Skeletons 4.2.2
		toms_storage: Tom's Simple Storage Mod 1.4.3
		toolstats: ToolStats 12.0.2
		tooltiprareness: Tooltip Rareness 1.0.7
		totw_additions: Towers of the Wild: Additions 1.2.3
		tradingpost: Trading Post 4.2.0
		transparent: Transparent 5.1.2
		travelersbackpack: Traveler's Backpack 1.19.2-8.2.5
		trinkets: Trinkets 3.4.0
		twigs: Twigs 2.0.0-beta.9+1.19-fabric
		twilightforest: The Twilight Forest 4.2.299
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			serialization_hooks: Serialization Hooks 0.3.22
			template: TEMPLATE 2.0.547+1.19.2
				porting_lib_base: Porting Lib Base 2.0.547+1.19.2
					com_github_llamalad7_mixinextras: MixinExtras 0.1.0-rc5
				porting_lib_entity: Porting Lib Entity 2.0.547+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.0.547+1.19.2
				porting_lib_models: Porting Lib Models 2.0.547+1.19.2
				porting_lib_networking: Porting Lib Networking 2.0.547+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.0.547+1.19.2
					porting_lib_model_loader: Porting Lib Model Loader 2.0.547+1.19.2
						porting_lib_extensions: Porting Lib Extensions 2.0.547+1.19.2
							porting_lib_accessors: Porting Lib Accessors 2.0.547+1.19.2
							porting_lib_attributes: Porting Lib Attributes 2.0.547+1.19.2
				porting_lib_tags: Porting Lib Tags 2.0.547+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.0.547+1.19.2
					porting_lib_common: Porting Lib Common 2.0.547+1.19.2
					porting_lib_constants: Porting Lib Constants 2.0.547+1.19.2
		veinmining: Vein Mining 1.0.0-beta.5+1.19.2
			spectrelib: SpectreLib 0.11.0+1.19
		villagernames: Villager Names 4.0.9
		visualworkbench: Visual Workbench 4.2.0
		voidtotem: Void Totem 2.1.0
		voidz: VoidZ 1.0.9
		windchimes: Windchimes 1.2.1
		wolveswitharmor: Wolves With Armor 1.8.0-1.19
			maybe-data: Maybe data 1.3.2-1.19-rc2
			static-content: Static Content 1.0.1-1.16.2
				staticdata: Static Data 1.1.2
		woof: Woof 2.0.2-1.19
		xps: Xp Obelisk 0.4.5.r_for_1.19.x_Fabric
		xps_additions: XP Obelisk Additions 0.1.3+1.19.x
		yigd: You're in Grave Danger 1.4.4
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.2
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
		yungsbridges: YUNG's Bridges 1.19.2-Fabric-3.1.0
		yungsextras: YUNG's Extras 1.19.2-Fabric-3.1.0
	Server Running: true
	Player Count: 2 / 4; [class_3222['FreddySeehauser'/88, l='ServerLevel[world]', x=-513.21, y=112.25, z=773.13], class_3222['Pedscim'/857, l='ServerLevel[world]', x=-497.58, y=99.00, z=-39.49]]
	Data Packs: vanilla, Fabric Mods, professions/fabric/normal, Everycomp Generated Pack, Snowyspirit Generated Pack, Supplementaries Generated Pack, dungeons-arise-1-19-v1-1.zip, ichphilipp-s-endcity-better-end-1-18-1.zip (incompatible), Repurposed_Structures-Better_Desert_Temples_v2.zip, Repurposed_Structures-Better_Dungeons_v4.zip, Repurposed_Structures-Better_Strongholds_v4.zip, Repurposed_Structures-Better_Witch_Huts_v3.zip, Repurposed_Structures-Bountiful_v2.zip, Repurposed_Structures-Farmers_Delight_v4.zip, Repurposed_Structures-Friends_And_Foes-v2.zip
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

### Other Mods

```shell
"the rest of medieval minecraft mods (1.19.2 - v9)
```

**Comment by quiqueck** [comment]
Thanks for reporting. Looks like this is an issue in combination with **rpgdifficulty**. Could you please try again without that specific mod?

**Comment by OmarE505** [comment]
so i disabled "naga" from the config file , and things seem to work fine so far , haven't had any other problems ! but i will let you know if anything else happen , thank you for the info tho !! and i hope you can come up with a solution soon <3 !
