### ISSUE TITLE
[Bug]  Repeated crash related to Naga (possible compatibility issue)

### ISSUE THREAD

**Issue by MecaZillaFox** [quiqueck/BetterNether#75]
### What happened?

I believe it's an incompatibility, but I have an issue with ticking-entity crashing whenever a whenever a Naga mob loads. I am unsure if it's every time a Naga loads or only specific ones as a ticking entity error, but I've yet to actually encounter a Naga outside of ones that crash my game so it makes me think it's the Naga itself. (Happened on two different worlds with the same result)

I think that it might be caused by mod RPG Difficulty based on the crash report, but I have not been able to test this because I don't know what file to put in RPG-Diff's mob exclusion (a bp file?) or how to change the spawns of Nagas to zero to see if either of that has an effect.

Preferably I would like to know how to turn the Naga spawns down to zero if possible, in case I'm wrong about the compatibility issue or crash cause. I hope you guys can help me out.

[crash-2022-11-04_11.20.26-server.txt](https://github.com/quiqueck/BetterNether/files/9940413/crash-2022-11-04_11.20.26-server.txt)

### BetterNether

7.1.1

### BCLib

2.1.2

### Fabric API

0.64.0

### Minecraft

1.19.2

### Relevant log output

```shell
-- Head --
Thread: Server thread
Stacktrace:
	at net.rpgdifficulty.api.MobStrengthener.changeAttributes(MobStrengthener.java:189)
	at net.minecraft.class_3218.handler$ifk000$spawnEntityMixin(class_3218.java:17215)
	at net.minecraft.class_3218.method_8649(class_3218.java)
	at org.betterx.betternether.entity.EntityNaga.method_7105(EntityNaga.java:60)
	at net.minecraft.class_1381.method_6268(class_1381.java:96)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:119)
	at net.minecraft.class_1355.method_6275(class_1355.java:110)
	at net.minecraft.class_1308.method_6023(class_1308.java:753)
	at net.minecraft.class_1309.method_6007(class_1309.java:2641)
	at net.minecraft.class_1308.method_6007(class_1308.java:553)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.minecraft.class_1309.method_5773(class_1309.java:2385)
	at net.minecraft.class_1308.method_5773(class_1308.java:353)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
Mixins in Stacktrace: None found

-- Entity being ticked --
Details:
	Entity Type: betternether:naga (org.betterx.betternether.entity.EntityNaga)
	Entity ID: 76
	Entity Name: Naga
	Entity's Exact location: -176.33, 59.00, 161.82
	Entity's Block location: World: (-177,59,161), Section: (at 15,11,1 in -12,3,10; chunk contains blocks -192,0,160 to -177,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
Mixins in Stacktrace: None found
```

### Other Mods

```shell
The Better Minecraft Modpack + 20~ additional mods including RPG Difficulty
```

**Comment by quiqueck** [comment]
Thanks for reporting. At a first glance I think this is an issue in MobStrengthener.

The code that is generating the crash is the naga projectile, not the naga itself:
https://github.com/quiqueck/BetterNether/blob/9a962ff12bcb69b021b5ae8c4fe590442869dd00/src/main/java/org/betterx/betternether/entity/EntityNaga.java#L57-L60

When the naga fires, we add that projectile entity to the world. This appears to the cause the crash in MobStrengthener, as the mod (probably) attempts to change some attributes for the projectile.

As I said, I think this is something you should report to the MobStrengthener team. However, if they think that our projectiles are the root cause, I will of course have a look.
