### ISSUE TITLE
[Bug] Crash when mining hoppers with ruby pickaxe

### ISSUE THREAD

**Issue by drown3d** [quiqueck/BetterNether#79]
### What happened?

Servers may crash when mining certain blocks, including hoppers, using a nether ruby pickaxe.

### BetterNether

6.1.2

### BCLib

1.4.7

### Fabric API

0.59.0

### Fabric Loader

0.14.9

### Minecraft

1.18.2

### Relevant log output

```shell
java.lang.IllegalArgumentException: No parameter <parameter minecraft:block_entity>
	at net.minecraft.loot.context.LootContext$Builder.get(LootContext:189)
	at net.minecraft.block.AbstractBlock.handler$eod000$setDroppedItemStackEnchantments(AbstractBlock:4032)
	at net.minecraft.block.AbstractBlock.getDroppedStacks(AbstractBlock:270)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.getDroppedStacks(AbstractBlock:935)
	at net.minecraft.block.Block.getDroppedStacks(Block:337)
	at paulevs.betternether.enchantments.RubyFire.getDrops(RubyFire.java:110)
	at net.minecraft.block.Block.handler$bba000$bn_getDrops(Block:2161)
	at net.minecraft.block.Block.dropStacks(Block)
	at net.minecraft.block.Block.afterBreak(Block:442)
	at net.minecraft.server.network.ServerPlayerInteractionManager.tryBreakBlock(ServerPlayerInteractionManager:276)
	at net.minecraft.server.network.ServerPlayerInteractionManager.update(ServerPlayerInteractionManager:104)
	at net.minecraft.server.network.ServerPlayerEntity.tick(ServerPlayerEntity:434)
	at net.minecraft.server.world.ServerWorld.redirect$gho000$shouldTickEntity(ServerWorld:20682)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:702)
	at net.minecraft.world.World.tickEntity(World:11091)
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:363)
	at net.minecraft.world.EntityList.forEach(EntityList:54)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:331)
	at net.minecraft.server.MinecraftServer.redirect$cfn000$fixUpdateSuppressionCrashTick(MinecraftServer:8290)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:907)
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:322)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:851)
	at net.minecraft.server.MinecraftServer.handler$boj000$modifiedRunLoop(MinecraftServer:7396)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273)
	at java.lang.Thread.run(Thread.java:833)
```

### Other Mods

```shell
Entity Texture Features - [Fabric & Forge] (by traben_0)
Cloth Config API (Fabric/Forge) (by shedaniel)
DragonLoot (by pois1xlive)
More Chat History (by JackFred2)
Charmonium (by svenhjol)
AdventureZ (by GloboxZ)
Don't Clear Chat History (by anar4732)
Faux Custom Entity Data (by Jaredlll08)
Patchouli (Fabric/Quilt) (by williewillus)
Player Roles (by gegy1000)
So Many Enchantments (by ShelterRin)
Your Options Shall Be Respected (YOSBR) (by shedaniel)
Archon (by safrodev)
Infusion Table (by jptrzy)
Better Compatibility Checker (by Gaz)
Forge Config API Port (by Fuzs_)
Cardinal Components (by UpcraftLP)
Balm (Fabric Edition) (by BlayTheNinth)
Language Reload (by Jerozgen)
Custom Entity Models (CEM) (by dorianpb)
LazyDFU (by tuxed)
Pehkui (by Virtuoel)
Starlight (Fabric) (by Spottedstar)
Awesome Dungeon The End edition - Fabric (by jtlelisa)
FancyMenu [Fabric] (by Keksuccino)
Konkrete [Fabric] (by Keksuccino)
KubeJS (by LatvianModder)
Sodium (by jellysquid3)
Controlling (by Jaredlll08)
Animatica (by FoundationGames)
Enchantment Descriptions (by DarkhaxDev)
Observable (by tasgon)
Awesome Dungeon Ocean edition - Fabric (by jtl_elisa)
Flan (by flemmli97)
Dynmap-Forge/Fabric (by Mikeprimm)
Smooth Boot (Fabric) (by UltimateBoomer)
BisectHosting Server Integration Menu [FABRIC] (by BisectHosting)
No Telemetry (by kb1000)
Imperishable Items (Fabric) (by ShaksterNano)
Fantasy Origins [Fabric] (by FroztiGaming)
BetterEnd (by Quiqueck)
Entity Culling Fabric/Forge (by tr9zw)
Awesome Dungeon Nether edition - Fabric (by jtl_elisa)
Mythical Origins (by proman468)
Extra Classes - Origins (by proman468)
XL Packets Fabric (by tfarecnim)
Icarus (by Camellias_)
Figura (by FrancyChan)
Ingredient Extension API (by Jaredlll08)
Iron Chests (Fabric) (by cyberanner)
CompleteConfig (by Lortseam)
BCLib (by Quiqueck)
Shoppy (by thethonk)
YUNG's Better Strongholds (Fabric) (by YUNGNICKYOUNG)
No Fade (by UltimateBoomer)
Dynamic FPS (by juliand665)
Indium (by comp500)
Mod Menu (by ProspectorDev)
MaLiLib (by masady)
Things [Fabric] (by gliscowo)
Repurposed Structures (Quilt/Fabric) (by telepathicgrunt)
An Origins Addon - Libra (by JaselUmena aka @JaselUmena )
Oh The Biomes You'll Go Refabricated (by AOCAWOL)
LambdaBetterGrass (by LambdAurora)
Fabric Language Kotlin (by modmuss50)
Aspects | Origins Addon (by fishplex)
Collective (Fabric) (by Serilum)
ToolTipFix (by Kyrptonaught)
Bosses of Mass Destruction (by Barribob)
YUNG's Better Mineshafts (Fabric) (by YUNGNICKYOUNG)
Fabrishot (by ramidzkh)
TooManyOrigins (by MerchantPug)
Charm (by svenhjol)
Anvil Fix (by UpcraftLP)
YUNG's API (Fabric) (by YUNGNICKYOUNG)
Fabric API (by modmuss50)
Simple Voice Chat (by henkelmax)
Savage Ender Dragon[Forge/Fabric] (by someaddon)
GeckoLib (by ThanosGecko)
AdvancementInfo (by Giselbaer)
Farsight [Fabric] (by someaddon)
Trinkets (Fabric) (by EmilyPloszaj)
Zoomify (by XanderIsDev)
Bewitchment (by MoriyaShiine)
Incantationem (by Luligabi12)
Bewitchment Plus (by MrSterner)
FTB Library (Fabric) (by FTB)
Better Mount HUD (by Lortseam)
FTB Teams (Fabric) (by FTB)
Inmis (by Draylar1)
BetterF3 (by cominixo)
Blockus (by Brandcraft_)
CreatePlus (by Yjn024)
Wolves With Armor (by Draylar1)
Bookshelf (by DarkhaxDev)
Friends&Foes (Fabric) (by faboslav)
Roughly Enough Items Fabric/Forge (REI) (by shedaniel)
Feature NBT Deadlock Be Gone (by telepathicgrunt)
Cloth Config API (UNUSED) (by shedaniel)
An Origins Addon - Apocalypse (by JaselUmena)
Bits And Chisels (by cool_mineman)
Mo' Structures (Fabric) (by ffrannny)
Botania (Fabric/Quilt) (by williewillus)
AntiGhost (by Giselbaer)
Very Many Players (Fabric) (by ishlandmc)
Vein Mining (Fabric) (by TheIllusiveC4)
TerraBlender (Fabric) (by TheAdubbz) 
Simple Discord RPC [Forge/Fabric/Quilt] (by hypherionsa)
Lithium (Fabric) (by jellysquid3_)
Extra Origins (by MoriyaShiine)
FerriteCore (Fabric) (by malte0811)
Rhino (by LatvianModder)
Ledger (by potatoboy99999)
Continuity (by Pepper_Bell)
Fabric Capes (by VictorKohler)
Enhanced Block Entities (by FoundationGames)
bad packets (by badasintended)
Waystones (Fabric Edition) (by BlayTheNinth)
spark (by Iucko)
MegaParrot (by SkylorBeck)
Borderless Mining (by comp500)
AppleSkin (by squeek502)
Pig Pen Cipher (by DarkhaxDev)
Architectury API (UNUSED) (by shedaniel)
Architectury API (Fabric/Forge) (by shedaniel)
Genesis - An Origins Addon (by PhantomereLive)
Origins: Classes (by Apace100)
Reese's Sodium Options (by FlashyReese)
Awesome Dungeon - Fabric (by jtl_elisa)
BetterNether (by Quiqueck)
Debugify (by XanderIsDev)
Login Protection[Forge/Fabric] (by someaddon)
Sodium Extra (by FlashyReese)
Create Fabric (by tropheusj)
WTHIT (by badasintended)
Lato Origins (by Slimeeq)
Iris Shaders (by coderbot)
Anvil Restoration (Fabric) (by Serilum)
Chunky (Fabric) (by pop4959)
Polymorph (Fabric) (by TheIllusiveC4)
CIT Resewn (by SHsuperCM)
Not Enough Crashes (Fabric) (by NatanFudge)
oωo (owo-lib) (by gliscowo)
Dark Utilities (by DarkhaxDev)
You're in Grave Danger (by b1n_ry)
Medieval Origins (by ItsParkieLad)
Mob Origins (by UltrusBot)
MrPlague's Warper Origin (by MrPlague04)
Iceberg [Fabric] (by Grend_G)
Origins (Fabric) (by Apace100)
JourneyMap (by techbrew)
Better Villages - Fabric (by jtl_elisa)
Origins Extra Keybinds (by thatrobin3001)
Puzzle (by Motschen)
Cloth API (Fabric) (by shedaniel)
ServerCore (by Wesley8081)
Cull Leaves (by Motschen)
Cosmetic Armor [FABRIC] (by Apace100)
Item Model Fix (Fabric) (by Pepper_Bell)
Library Ferret - Fabric (by jtl_elisa)
Advancement Plaques [Fabric] (by Grend_G)
VoidZ (by Globox_Z)
MidnightLib (by TeamMidnightDust)
Runelic (by DarkhaxDev)
Chisel Refabricated (by Slaincow)
WorldEdit (by sk89q)
Reborn Core (by modmuss50)
```

**Comment by quiqueck** [comment]
7.x protects that part of the code against crashes now, so while the issue itself may still be there, it will not crash the game
