### ISSUE TITLE
[Bug] Crashing on load

### ISSUE THREAD

**Issue by SleepyCatten** [quiqueck/BetterNether#98]
### What happened?

Crashing on load

### BetterNether

8.1.2

### BCLib

2.2.3

### Fabric API

0.70.0+1.19.3

### Fabric Loader

0.14.12

### Minecraft

1.19.3

### Relevant log output

```shell
[23:23:57] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.12
[23:23:57] [main/INFO]: Loading 42 mods:
	- bclib 2.2.3
	- betternether 8.1.2
	- fabric-api 0.70.0+1.19.3
	- fabric-api-base 0.4.20+afca2f3e85 via fabric-api
	- fabric-api-lookup-api-v1 1.6.19+49abcf7e85 via fabric-api
	- fabric-biome-api-v1 12.0.1+f1e4495b85 via fabric-api
	- fabric-block-api-v1 1.0.4+e022e5d185 via fabric-api
	- fabric-command-api-v1 1.2.20+f71b366f85 via fabric-api
	- fabric-command-api-v2 2.1.16+99f9db8085 via fabric-api
	- fabric-commands-v0 0.2.37+df3654b385 via fabric-api
	- fabric-containers-v0 0.1.45+df3654b385 via fabric-api
	- fabric-content-registries-v0 3.5.0+1d37d50285 via fabric-api
	- fabric-convention-tags-v1 1.2.1+8e4e694f85 via fabric-api
	- fabric-crash-report-info-v1 0.2.13+aeb40ebe85 via fabric-api
	- fabric-data-generation-api-v1 11.1.2+33a4e2d785 via fabric-api
	- fabric-dimensions-v1 2.1.40+48349a3f85 via fabric-api
	- fabric-entity-events-v1 1.5.6+b83334a085 via fabric-api
	- fabric-events-interaction-v0 0.4.38+f1e4495b85 via fabric-api
	- fabric-events-lifecycle-v0 0.2.40+df3654b385 via fabric-api
	- fabric-game-rule-api-v1 1.0.29+99f9db8085 via fabric-api
	- fabric-item-api-v1 2.1.6+99f9db8085 via fabric-api
	- fabric-item-group-api-v1 2.1.9+d3d735d085 via fabric-api
	- fabric-lifecycle-events-v1 2.2.9+23a79c8a85 via fabric-api
	- fabric-loot-api-v2 1.1.19+75e9821185 via fabric-api
	- fabric-loot-tables-v1 1.1.23+9e7660c685 via fabric-api
	- fabric-message-api-v1 5.0.13+6ede1da985 via fabric-api
	- fabric-mining-level-api-v1 2.1.30+49abcf7e85 via fabric-api
	- fabric-networking-api-v1 1.2.15+99f9db8085 via fabric-api
	- fabric-networking-v0 0.3.32+df3654b385 via fabric-api
	- fabric-object-builder-api-v1 5.2.1+f1e4495b85 via fabric-api
	- fabric-particles-v1 1.0.19+f1e4495b85 via fabric-api
	- fabric-registry-sync-v0 2.0.2+2608564685 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.24+afca2f3e85 via fabric-api
	- fabric-rendering-fluids-v1 3.0.17+f1e4495b85 via fabric-api
	- fabric-resource-conditions-api-v1 2.2.1+280be3ab85 via fabric-api
	- fabric-resource-loader-v0 0.10.4+a91e48b785 via fabric-api
	- fabric-screen-handler-api-v1 1.3.11+99f9db8085 via fabric-api
	- fabric-transfer-api-v1 2.1.13+f1e4495b85 via fabric-api
	- fabric-transitive-access-wideners-v1 2.2.0+1d37d50285 via fabric-api
	- fabricloader 0.14.12
	- java 19
	- minecraft 1.19.3
[23:23:57] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Games/MC%20Server%20Soft/servers/Cult%20Of%20Shiv%20Fabric%20Server%20Test/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[23:23:58] [main/INFO]: Compatibility level set to JAVA_17
[23:24:02] [main/INFO]: Building unoptimized datafixer
[23:24:03] [main/INFO]: [bclib] Added Config betternether.main to auto sync (file hash)
[23:24:03] [main/INFO]: [bclib] Added Config betternether.generator to auto sync (file hash)
[23:24:03] [main/INFO]: [bclib] Added Config betternether.blocks to auto sync (file hash)
[23:24:03] [main/INFO]: [bclib] Added Config betternether.items to auto sync (file hash)
[23:24:03] [main/INFO]: [bclib] Added Config betternether.biomes to auto sync (file hash)
[23:24:03] [main/INFO]: [bclib] Added Config betternether.mobs to auto sync (file hash)
[23:24:03] [main/INFO]: [bclib] Added Config betternether.recipes to auto sync (file hash)
[23:24:04] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: net/minecraft/class_554
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric.jar:0.11.1]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_554
	at org.betterx.betternether.registry.NetherItems.<clinit>(NetherItems.java:150) ~[better-nether-8.1.2.jar:?]
	at org.betterx.betternether.blocks.complex.NetherWoodenMaterial.init(NetherWoodenMaterial.java:69) ~[better-nether-8.1.2.jar:?]
	at org.betterx.betternether.blocks.complex.RoofMaterial.init(RoofMaterial.java:29) ~[better-nether-8.1.2.jar:?]
	at org.betterx.betternether.blocks.complex.NetherReedMaterial.init(NetherReedMaterial.java:58) ~[better-nether-8.1.2.jar:?]
	at org.betterx.betternether.registry.NetherBlocks.<clinit>(NetherBlocks.java:43) ~[better-nether-8.1.2.jar:?]
	at org.betterx.betternether.entity.EntityFirefly.<clinit>(EntityFirefly.java:549) ~[better-nether-8.1.2.jar:?]
	at org.betterx.betternether.registry.NetherEntities.<clinit>(NetherEntities.java:153) ~[better-nether-8.1.2.jar:?]
	at net.minecraft.class_5135.handler$zdc000$hasDefinition(class_5135.java:531) ~[server-intermediary.jar:?]
	at net.minecraft.class_5135.method_26875(class_5135.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_5135.method_26876(class_5135.java:178) ~[server-intermediary.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.class_5135.method_26872(class_5135.java:180) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_17598(class_2966.java:127) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:100) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	... 4 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_554
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at org.betterx.betternether.registry.NetherItems.<clinit>(NetherItems.java:150) ~[better-nether-8.1.2.jar:?]
	at org.betterx.betternether.blocks.complex.NetherWoodenMaterial.init(NetherWoodenMaterial.java:69) ~[better-nether-8.1.2.jar:?]
	at org.betterx.betternether.blocks.complex.RoofMaterial.init(RoofMaterial.java:29) ~[better-nether-8.1.2.jar:?]
	at org.betterx.betternether.blocks.complex.NetherReedMaterial.init(NetherReedMaterial.java:58) ~[better-nether-8.1.2.jar:?]
	at org.betterx.betternether.registry.NetherBlocks.<clinit>(NetherBlocks.java:43) ~[better-nether-8.1.2.jar:?]
	at org.betterx.betternether.entity.EntityFirefly.<clinit>(EntityFirefly.java:549) ~[better-nether-8.1.2.jar:?]
	at org.betterx.betternether.registry.NetherEntities.<clinit>(NetherEntities.java:153) ~[better-nether-8.1.2.jar:?]
	at net.minecraft.class_5135.handler$zdc000$hasDefinition(class_5135.java:531) ~[server-intermediary.jar:?]
	at net.minecraft.class_5135.method_26875(class_5135.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_5135.method_26876(class_5135.java:178) ~[server-intermediary.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.class_5135.method_26872(class_5135.java:180) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_17598(class_2966.java:127) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:100) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	... 4 more
```

**Comment by fampat** [comment]
Same for me when running a headless server, seemd like it currently is dependent on an client to work.

**Comment by quiqueck** [comment]
Will be fixed in the upcoming update :)

**Comment by exavian** [comment]
Found myself having this same issue just before you pushed the new update. I can confirm that that issue is no longer occurring, but now my server crashes instead because of a NullPointerException. If I remove Better(Dimensions) and BCLib the server runs fine. Has anyone else reported such an issue?

**Comment by quiqueck** [comment]
Could you please post your logs?

**Comment by exavian** [comment]
Of course! I did a fresh attempt a moment ago and here's the logs of that:

Console log: https://mcpaste.io/b69b571f052a69b5
Log file: https://mcpaste.io/3d6192623f7e5bb8

If there's anything else helpful I can provide or do, I'd be happy to.

**Comment by exavian** [comment]
@quiqueck Not sure if you've looked into this at all, but I'm guessing it's the same problem that was reported here on the BCLib repo: https://github.com/quiqueck/BCLib/issues/72

**Comment by AliahX** [comment]
I've got the same issue. the logs are identical where the error is.

**Comment by randoART** [comment]
> Will be fixed in the upcoming update :)



this same  thing is happening to  me in 1.20.1 version 9.0.9
